// Code generated by ent, DO NOT EDIT.

package compositemodelroute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the compositemodelroute type in the database.
	Label = "composite_model_route"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldParentGroupID holds the string denoting the parent_group_id field in the database.
	FieldParentGroupID = "parent_group_id"
	// FieldDisplayModelID holds the string denoting the display_model_id field in the database.
	FieldDisplayModelID = "display_model_id"
	// FieldTargetGroupID holds the string denoting the target_group_id field in the database.
	FieldTargetGroupID = "target_group_id"
	// FieldTargetModelID holds the string denoting the target_model_id field in the database.
	FieldTargetModelID = "target_model_id"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeParentGroup holds the string denoting the parent_group edge name in mutations.
	EdgeParentGroup = "parent_group"
	// EdgeTargetGroup holds the string denoting the target_group edge name in mutations.
	EdgeTargetGroup = "target_group"
	// Table holds the table name of the compositemodelroute in the database.
	Table = "composite_model_routes"
	// ParentGroupTable is the table that holds the parent_group relation/edge.
	ParentGroupTable = "composite_model_routes"
	// ParentGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	ParentGroupInverseTable = "groups"
	// ParentGroupColumn is the table column denoting the parent_group relation/edge.
	ParentGroupColumn = "parent_group_id"
	// TargetGroupTable is the table that holds the target_group relation/edge.
	TargetGroupTable = "composite_model_routes"
	// TargetGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	TargetGroupInverseTable = "groups"
	// TargetGroupColumn is the table column denoting the target_group relation/edge.
	TargetGroupColumn = "target_group_id"
)

// Columns holds all SQL columns for compositemodelroute fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldParentGroupID,
	FieldDisplayModelID,
	FieldTargetGroupID,
	FieldTargetModelID,
	FieldPriority,
	FieldEnabled,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DisplayModelIDValidator is a validator for the "display_model_id" field. It is called by the builders before save.
	DisplayModelIDValidator func(string) error
	// DefaultTargetModelID holds the default value on creation for the "target_model_id" field.
	DefaultTargetModelID string
	// TargetModelIDValidator is a validator for the "target_model_id" field. It is called by the builders before save.
	TargetModelIDValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
)

// OrderOption defines the ordering options for the CompositeModelRoute queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByParentGroupID orders the results by the parent_group_id field.
func ByParentGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentGroupID, opts...).ToFunc()
}

// ByDisplayModelID orders the results by the display_model_id field.
func ByDisplayModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayModelID, opts...).ToFunc()
}

// ByTargetGroupID orders the results by the target_group_id field.
func ByTargetGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetGroupID, opts...).ToFunc()
}

// ByTargetModelID orders the results by the target_model_id field.
func ByTargetModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetModelID, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByParentGroupField orders the results by parent_group field.
func ByParentGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetGroupField orders the results by target_group field.
func ByTargetGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newParentGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ParentGroupTable, ParentGroupColumn),
	)
}
func newTargetGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TargetGroupTable, TargetGroupColumn),
	)
}
