// Code generated by ent, DO NOT EDIT.

package compositemodelroute

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// ParentGroupID applies equality check predicate on the "parent_group_id" field. It's identical to ParentGroupIDEQ.
func ParentGroupID(v int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldParentGroupID, v))
}

// DisplayModelID applies equality check predicate on the "display_model_id" field. It's identical to DisplayModelIDEQ.
func DisplayModelID(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldDisplayModelID, v))
}

// TargetGroupID applies equality check predicate on the "target_group_id" field. It's identical to TargetGroupIDEQ.
func TargetGroupID(v int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldTargetGroupID, v))
}

// TargetModelID applies equality check predicate on the "target_model_id" field. It's identical to TargetModelIDEQ.
func TargetModelID(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldTargetModelID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldEnabled, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldUpdatedAt, v))
}

// ParentGroupIDEQ applies the EQ predicate on the "parent_group_id" field.
func ParentGroupIDEQ(v int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldParentGroupID, v))
}

// ParentGroupIDNEQ applies the NEQ predicate on the "parent_group_id" field.
func ParentGroupIDNEQ(v int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldParentGroupID, v))
}

// ParentGroupIDIn applies the In predicate on the "parent_group_id" field.
func ParentGroupIDIn(vs ...int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldParentGroupID, vs...))
}

// ParentGroupIDNotIn applies the NotIn predicate on the "parent_group_id" field.
func ParentGroupIDNotIn(vs ...int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldParentGroupID, vs...))
}

// DisplayModelIDEQ applies the EQ predicate on the "display_model_id" field.
func DisplayModelIDEQ(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldDisplayModelID, v))
}

// DisplayModelIDNEQ applies the NEQ predicate on the "display_model_id" field.
func DisplayModelIDNEQ(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldDisplayModelID, v))
}

// DisplayModelIDIn applies the In predicate on the "display_model_id" field.
func DisplayModelIDIn(vs ...string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldDisplayModelID, vs...))
}

// DisplayModelIDNotIn applies the NotIn predicate on the "display_model_id" field.
func DisplayModelIDNotIn(vs ...string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldDisplayModelID, vs...))
}

// DisplayModelIDGT applies the GT predicate on the "display_model_id" field.
func DisplayModelIDGT(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldDisplayModelID, v))
}

// DisplayModelIDGTE applies the GTE predicate on the "display_model_id" field.
func DisplayModelIDGTE(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldDisplayModelID, v))
}

// DisplayModelIDLT applies the LT predicate on the "display_model_id" field.
func DisplayModelIDLT(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldDisplayModelID, v))
}

// DisplayModelIDLTE applies the LTE predicate on the "display_model_id" field.
func DisplayModelIDLTE(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldDisplayModelID, v))
}

// DisplayModelIDContains applies the Contains predicate on the "display_model_id" field.
func DisplayModelIDContains(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldContains(FieldDisplayModelID, v))
}

// DisplayModelIDHasPrefix applies the HasPrefix predicate on the "display_model_id" field.
func DisplayModelIDHasPrefix(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldHasPrefix(FieldDisplayModelID, v))
}

// DisplayModelIDHasSuffix applies the HasSuffix predicate on the "display_model_id" field.
func DisplayModelIDHasSuffix(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldHasSuffix(FieldDisplayModelID, v))
}

// DisplayModelIDEqualFold applies the EqualFold predicate on the "display_model_id" field.
func DisplayModelIDEqualFold(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEqualFold(FieldDisplayModelID, v))
}

// DisplayModelIDContainsFold applies the ContainsFold predicate on the "display_model_id" field.
func DisplayModelIDContainsFold(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldContainsFold(FieldDisplayModelID, v))
}

// TargetGroupIDEQ applies the EQ predicate on the "target_group_id" field.
func TargetGroupIDEQ(v int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldTargetGroupID, v))
}

// TargetGroupIDNEQ applies the NEQ predicate on the "target_group_id" field.
func TargetGroupIDNEQ(v int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldTargetGroupID, v))
}

// TargetGroupIDIn applies the In predicate on the "target_group_id" field.
func TargetGroupIDIn(vs ...int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldTargetGroupID, vs...))
}

// TargetGroupIDNotIn applies the NotIn predicate on the "target_group_id" field.
func TargetGroupIDNotIn(vs ...int64) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldTargetGroupID, vs...))
}

// TargetModelIDEQ applies the EQ predicate on the "target_model_id" field.
func TargetModelIDEQ(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldTargetModelID, v))
}

// TargetModelIDNEQ applies the NEQ predicate on the "target_model_id" field.
func TargetModelIDNEQ(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldTargetModelID, v))
}

// TargetModelIDIn applies the In predicate on the "target_model_id" field.
func TargetModelIDIn(vs ...string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldTargetModelID, vs...))
}

// TargetModelIDNotIn applies the NotIn predicate on the "target_model_id" field.
func TargetModelIDNotIn(vs ...string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldTargetModelID, vs...))
}

// TargetModelIDGT applies the GT predicate on the "target_model_id" field.
func TargetModelIDGT(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldTargetModelID, v))
}

// TargetModelIDGTE applies the GTE predicate on the "target_model_id" field.
func TargetModelIDGTE(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldTargetModelID, v))
}

// TargetModelIDLT applies the LT predicate on the "target_model_id" field.
func TargetModelIDLT(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldTargetModelID, v))
}

// TargetModelIDLTE applies the LTE predicate on the "target_model_id" field.
func TargetModelIDLTE(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldTargetModelID, v))
}

// TargetModelIDContains applies the Contains predicate on the "target_model_id" field.
func TargetModelIDContains(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldContains(FieldTargetModelID, v))
}

// TargetModelIDHasPrefix applies the HasPrefix predicate on the "target_model_id" field.
func TargetModelIDHasPrefix(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldHasPrefix(FieldTargetModelID, v))
}

// TargetModelIDHasSuffix applies the HasSuffix predicate on the "target_model_id" field.
func TargetModelIDHasSuffix(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldHasSuffix(FieldTargetModelID, v))
}

// TargetModelIDEqualFold applies the EqualFold predicate on the "target_model_id" field.
func TargetModelIDEqualFold(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEqualFold(FieldTargetModelID, v))
}

// TargetModelIDContainsFold applies the ContainsFold predicate on the "target_model_id" field.
func TargetModelIDContainsFold(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldContainsFold(FieldTargetModelID, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldEnabled, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.FieldContainsFold(FieldNotes, v))
}

// HasParentGroup applies the HasEdge predicate on the "parent_group" edge.
func HasParentGroup() predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ParentGroupTable, ParentGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentGroupWith applies the HasEdge predicate on the "parent_group" edge with a given conditions (other predicates).
func HasParentGroupWith(preds ...predicate.Group) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(func(s *sql.Selector) {
		step := newParentGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetGroup applies the HasEdge predicate on the "target_group" edge.
func HasTargetGroup() predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TargetGroupTable, TargetGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetGroupWith applies the HasEdge predicate on the "target_group" edge with a given conditions (other predicates).
func HasTargetGroupWith(preds ...predicate.Group) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(func(s *sql.Selector) {
		step := newTargetGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CompositeModelRoute) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CompositeModelRoute) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CompositeModelRoute) predicate.CompositeModelRoute {
	return predicate.CompositeModelRoute(sql.NotPredicates(p))
}
