// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/Wei-Shaw/sub2api/internal/handler"
	"github.com/Wei-Shaw/sub2api/internal/handler/admin"
	"github.com/Wei-Shaw/sub2api/internal/repository"
	"github.com/Wei-Shaw/sub2api/internal/server"
	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/redis/go-redis/v9"
	"log"
	"net/http"
	"sync"
	"time"
)

import (
	_ "embed"
	_ "github.com/Wei-Shaw/sub2api/ent/runtime"
)

// Injectors from wire.go:

func initializeApplication(buildInfo handler.BuildInfo) (*Application, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	client, err := repository.ProvideEnt(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := repository.ProvideSQLDB(client)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(client, db)
	authIdentityRepository := repository.NewAuthIdentityRepository(db)
	redeemCodeRepository := repository.NewRedeemCodeRepository(client)
	redisClient := repository.ProvideRedis(configConfig)
	refreshTokenCache := repository.NewRefreshTokenCache(redisClient)
	settingRepository := repository.NewSettingRepository(client)
	groupRepository := repository.NewGroupRepository(client, db)
	settingService := service.ProvideSettingService(settingRepository, groupRepository, configConfig)
	emailCache := repository.NewEmailCache(redisClient)
	emailTemplateRepository := repository.NewEmailTemplateRepository(db)
	emailTemplateService := service.NewEmailTemplateService(emailTemplateRepository)
	emailService := service.ProvideEmailService(settingRepository, emailCache, emailTemplateService)
	turnstileVerifier := repository.NewTurnstileVerifier()
	turnstileService := service.NewTurnstileService(settingService, turnstileVerifier)
	emailQueueService := service.ProvideEmailQueueService(emailService)
	promoCodeRepository := repository.NewPromoCodeRepository(client)
	billingCache := repository.NewBillingCache(redisClient)
	userSubscriptionRepository := repository.NewUserSubscriptionRepository(client)
	apiKeyRepository := repository.NewAPIKeyRepository(client, db)
	userPlatformQuotaRepository := repository.NewUserPlatformQuotaRepository(client, db)
	userPlatformQuotaService := service.NewUserPlatformQuotaService(userPlatformQuotaRepository)
	billingCacheService := service.ProvideBillingCacheService(billingCache, userRepository, userSubscriptionRepository, apiKeyRepository, configConfig, userPlatformQuotaService, settingService)
	userGroupRateRepository := repository.NewUserGroupRateRepository(db)
	apiKeyCache := repository.NewAPIKeyCache(redisClient)
	pricingRemoteClient := repository.ProvidePricingRemoteClient(configConfig)
	pricingService, err := service.ProvidePricingService(configConfig, pricingRemoteClient)
	if err != nil {
		return nil, err
	}
	billingService := service.NewBillingService(configConfig, pricingService)
	schedulerCache := repository.NewSchedulerCache(redisClient)
	accountRepository := repository.NewAccountRepository(client, db, schedulerCache)
	modelRegistryService := service.ProvideModelRegistryService(settingRepository, accountRepository)
	channelMonitorRepository := repository.NewChannelMonitorRepository(db)
	channelMonitorHistoryRepository := repository.NewChannelMonitorHistoryRepository(db)
	channelMonitorRollupRepository := repository.NewChannelMonitorRollupRepository(db)
	secretEncryptor, err := repository.NewAESEncryptor(configConfig)
	if err != nil {
		return nil, err
	}
	channelMonitorService := service.NewChannelMonitorService(channelMonitorRepository, channelMonitorHistoryRepository, channelMonitorRollupRepository, settingService, secretEncryptor, configConfig)
	modelCatalogService := service.ProvideModelCatalogService(settingRepository, apiKeyRepository, userPlatformQuotaService, billingService, pricingService, modelRegistryService, channelMonitorService, configConfig)
	apiKeyService := service.ProvideAPIKeyService(apiKeyRepository, userRepository, groupRepository, userSubscriptionRepository, userGroupRateRepository, apiKeyCache, billingCacheService, modelCatalogService, settingService, configConfig)
	apiKeyAuthCacheInvalidator := service.ProvideAPIKeyAuthCacheInvalidator(apiKeyService, billingCacheService)
	promoService := service.NewPromoService(promoCodeRepository, userRepository, billingCacheService, client, apiKeyAuthCacheInvalidator)
	affiliateRepository := repository.NewAffiliateRepository(client, db)
	affiliateService := service.ProvideAffiliateService(settingService, affiliateRepository, billingCacheService, apiKeyAuthCacheInvalidator)
	subscriptionService := service.NewSubscriptionService(groupRepository, userSubscriptionRepository, billingCacheService, client, configConfig)
	authService := service.ProvideAuthService(client, userRepository, authIdentityRepository, redeemCodeRepository, refreshTokenCache, configConfig, settingService, emailService, turnstileService, emailQueueService, promoService, affiliateService, subscriptionService)
	userService := service.NewUserService(userRepository, apiKeyAuthCacheInvalidator, billingCache)
	redeemCache := repository.NewRedeemCache(redisClient)
	redeemService := service.NewRedeemService(redeemCodeRepository, userRepository, subscriptionService, redeemCache, billingCacheService, client, apiKeyAuthCacheInvalidator, affiliateService)
	totpCache := repository.NewTotpCache(redisClient)
	totpService := service.NewTotpService(userRepository, secretEncryptor, totpCache, settingService, emailService, emailQueueService)
	authIdentityService := service.NewAuthIdentityService(authIdentityRepository, userRepository, authService)
	userAttributeDefinitionRepository := repository.NewUserAttributeDefinitionRepository(client)
	userAttributeValueRepository := repository.NewUserAttributeValueRepository(client)
	userAttributeService := service.NewUserAttributeService(userAttributeDefinitionRepository, userAttributeValueRepository)
	authHandler := handler.ProvideAuthHandler(configConfig, authService, userService, settingService, promoService, redeemService, totpService, authIdentityService, userAttributeService)
	userHandler := handler.ProvideUserHandler(userService, affiliateService, authIdentityService, emailTemplateService, userPlatformQuotaService)
	metaHandler := handler.ProvideMetaHandler(modelCatalogService, modelRegistryService, settingService, authService, userService)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	channelRepository := repository.NewChannelRepository(db)
	channelService := service.NewChannelService(channelRepository, groupRepository, pricingService)
	availableChannelHandler := handler.NewAvailableChannelHandler(channelService, apiKeyService, settingService)
	channelMonitorHandler := handler.NewChannelMonitorHandler(channelMonitorService)
	usageLogRepository := repository.NewUsageLogRepository(client, db)
	usageService := service.ProvideUsageService(usageLogRepository, userRepository, client, apiKeyAuthCacheInvalidator, emailService, emailTemplateService)
	usageHandler := handler.NewUsageHandler(usageService, apiKeyService)
	redeemHandler := handler.NewRedeemHandler(redeemService)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionService)
	announcementRepository := repository.NewAnnouncementRepository(client)
	announcementReadRepository := repository.NewAnnouncementReadRepository(client)
	announcementService := service.NewAnnouncementService(announcementRepository, announcementReadRepository, userRepository, userSubscriptionRepository)
	announcementHandler := handler.NewAnnouncementHandler(announcementService)
	dashboardAggregationRepository := repository.NewDashboardAggregationRepository(db)
	dashboardStatsCache := repository.NewDashboardCache(redisClient, configConfig)
	dashboardService := service.NewDashboardService(usageLogRepository, dashboardAggregationRepository, dashboardStatsCache, configConfig)
	timingWheelService, err := service.ProvideTimingWheelService()
	if err != nil {
		return nil, err
	}
	dashboardAggregationService := service.ProvideDashboardAggregationService(dashboardAggregationRepository, timingWheelService, configConfig)
	dashboardHandler := admin.NewDashboardHandler(dashboardService, dashboardAggregationService)
	proxyRepository := repository.NewProxyRepository(client, db)
	proxyExitInfoProber := repository.NewProxyExitInfoProber(configConfig)
	proxyLatencyCache := repository.NewProxyLatencyCache(redisClient)
	privacyClientFactory := repository.ProvidePrivacyClientFactory()
	adminService := service.NewAdminService(userRepository, groupRepository, accountRepository, proxyRepository, apiKeyRepository, redeemCodeRepository, userGroupRateRepository, billingCacheService, proxyExitInfoProber, proxyLatencyCache, apiKeyAuthCacheInvalidator, privacyClientFactory, client, settingService, subscriptionService, userSubscriptionRepository, affiliateService, configConfig)
	concurrencyCache := repository.ProvideConcurrencyCache(redisClient, configConfig)
	concurrencyService := service.ProvideConcurrencyService(concurrencyCache, accountRepository, configConfig)
	adminUserHandler := handler.ProvideAdminUserHandler(adminService, concurrencyService, userPlatformQuotaService)
	contentModerationAuditRepository := repository.NewContentModerationAuditRepository(db)
	contentModerationService := service.NewContentModerationService(contentModerationAuditRepository, settingRepository)
	contentModerationAuditHandler := admin.NewContentModerationAuditHandler(contentModerationService)
	sessionLimitCache := repository.ProvideSessionLimitCache(redisClient, configConfig)
	rpmCache := repository.NewRPMCache(redisClient)
	groupCapacityService := service.NewGroupCapacityService(accountRepository, groupRepository, concurrencyService, sessionLimitCache, rpmCache)
	groupHandler := admin.NewGroupHandler(adminService, dashboardService, groupCapacityService)
	channelHandler := admin.NewChannelHandler(channelService)
	adminChannelMonitorHandler := admin.NewChannelMonitorHandler(channelMonitorService)
	channelMonitorTemplateRepository := repository.NewChannelMonitorTemplateRepository(db)
	channelMonitorTemplateService := service.NewChannelMonitorTemplateService(channelMonitorTemplateRepository, channelMonitorRepository)
	channelMonitorTemplateHandler := admin.NewChannelMonitorTemplateHandler(channelMonitorTemplateService, channelMonitorService)
	claudeOAuthClient := repository.NewClaudeOAuthClient()
	oAuthService := service.NewOAuthService(proxyRepository, claudeOAuthClient)
	openAIOAuthClient := repository.NewOpenAIOAuthClient()
	openAIOAuthService := service.NewOpenAIOAuthService(proxyRepository, openAIOAuthClient)
	kiroOAuthClient := repository.NewKiroOAuthClient()
	kiroOAuthService := service.NewKiroOAuthService(proxyRepository, kiroOAuthClient)
	geminiOAuthClient := repository.NewGeminiOAuthClient(configConfig)
	geminiCliCodeAssistClient := repository.NewGeminiCliCodeAssistClient()
	driveClient := repository.NewGeminiDriveClient()
	geminiOAuthService := service.NewGeminiOAuthService(proxyRepository, geminiOAuthClient, geminiCliCodeAssistClient, driveClient, configConfig)
	antigravityOAuthService := service.NewAntigravityOAuthService(proxyRepository)
	geminiQuotaService := service.NewGeminiQuotaService(configConfig, settingRepository)
	tempUnschedCache := repository.NewTempUnschedCache(redisClient)
	timeoutCounterCache := repository.NewTimeoutCounterCache(redisClient)
	geminiTokenCache := repository.NewGeminiTokenCache(redisClient)
	compositeTokenCacheInvalidator := service.NewCompositeTokenCacheInvalidator(geminiTokenCache)
	rateLimitService := service.ProvideRateLimitService(accountRepository, usageLogRepository, configConfig, geminiQuotaService, tempUnschedCache, timeoutCounterCache, settingService, compositeTokenCacheInvalidator)
	httpUpstream := repository.NewHTTPUpstream(configConfig)
	claudeUsageFetcher := repository.NewClaudeUsageFetcher(httpUpstream)
	antigravityQuotaFetcher := service.NewAntigravityQuotaFetcher(proxyRepository)
	usageCache := service.NewUsageCache()
	identityCache := repository.NewIdentityCache(redisClient)
	tlsFingerprintProfileRepository := repository.NewTLSFingerprintProfileRepository(client)
	tlsFingerprintProfileCache := repository.NewTLSFingerprintProfileCache(redisClient)
	tlsFingerprintProfileService := service.ProvideTLSFingerprintProfileService(tlsFingerprintProfileRepository, tlsFingerprintProfileCache)
	accountUsageService := service.ProvideAccountUsageService(accountRepository, usageLogRepository, claudeUsageFetcher, geminiQuotaService, antigravityQuotaFetcher, usageCache, identityCache, tlsFingerprintProfileService)
	upstreamResourceBindingRepository := repository.NewUpstreamResourceBindingRepository(db)
	googleBatchQuotaReservationRepository := repository.NewGoogleBatchQuotaReservationRepository(db)
	googleBatchArchiveJobRepository := repository.NewGoogleBatchArchiveJobRepository(db)
	googleBatchArchiveObjectRepository := repository.NewGoogleBatchArchiveObjectRepository(db)
	gatewayCache := repository.NewGatewayCache(redisClient)
	schedulerOutboxRepository := repository.NewSchedulerOutboxRepository(db)
	schedulerSnapshotService := service.ProvideSchedulerSnapshotService(schedulerCache, schedulerOutboxRepository, accountRepository, groupRepository, configConfig)
	oAuthRefreshAPI := service.ProvideOAuthRefreshAPI(accountRepository, geminiTokenCache)
	geminiTokenProvider := service.ProvideGeminiTokenProvider(accountRepository, geminiTokenCache, geminiOAuthService, oAuthRefreshAPI)
	usageBillingRepository := repository.NewUsageBillingRepository(client, db)
	googleBatchArchiveStorage := service.ProvideGoogleBatchArchiveStorage()
	antigravityTokenProvider := service.ProvideAntigravityTokenProvider(accountRepository, geminiTokenCache, antigravityOAuthService, oAuthRefreshAPI, tempUnschedCache)
	antigravityGatewayService := service.NewAntigravityGatewayService(accountRepository, gatewayCache, schedulerSnapshotService, antigravityTokenProvider, rateLimitService, httpUpstream, settingService)
	geminiMessagesCompatService := service.ProvideGeminiMessagesCompatService(accountRepository, apiKeyRepository, groupRepository, upstreamResourceBindingRepository, googleBatchQuotaReservationRepository, googleBatchArchiveJobRepository, googleBatchArchiveObjectRepository, gatewayCache, schedulerSnapshotService, geminiTokenProvider, rateLimitService, billingService, usageLogRepository, usageBillingRepository, settingService, googleBatchArchiveStorage, modelCatalogService, httpUpstream, antigravityGatewayService, configConfig)
	vertexUpstreamCatalogService := service.ProvideVertexUpstreamCatalogService(httpUpstream, geminiTokenProvider, proxyRepository, configConfig)
	openAITokenProvider := service.ProvideOpenAITokenProvider(accountRepository, geminiTokenCache, openAIOAuthService, oAuthRefreshAPI)
	claudeTokenProvider := service.ProvideClaudeTokenProvider(accountRepository, geminiTokenCache, oAuthService, kiroOAuthService, oAuthRefreshAPI)
	kiroRuntimeService := service.NewKiroRuntimeService(accountRepository, httpUpstream, claudeTokenProvider)
	accountModelImportService := service.ProvideAccountModelImportService(modelCatalogService, modelRegistryService, geminiMessagesCompatService, vertexUpstreamCatalogService, openAITokenProvider, kiroRuntimeService, httpUpstream, proxyRepository, tlsFingerprintProfileService, configConfig)
	identityService := service.NewIdentityService(identityCache)
	deferredService := service.ProvideDeferredService(accountRepository, timingWheelService)
	digestSessionStore := service.NewDigestSessionStore()
	gatewayService := service.ProvideGatewayService(accountRepository, groupRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, identityService, httpUpstream, deferredService, claudeTokenProvider, sessionLimitCache, rpmCache, digestSessionStore, settingService, modelRegistryService, modelCatalogService, apiKeyService, channelService, vertexUpstreamCatalogService, tlsFingerprintProfileService)
	grokReverseClient := service.NewGrokReverseClient(httpUpstream, configConfig)
	grokGatewayService := service.NewGrokGatewayService(gatewayService, httpUpstream, rateLimitService, grokReverseClient, configConfig)
	openAIGatewayService := service.ProvideOpenAIGatewayService(accountRepository, usageLogRepository, usageBillingRepository, userRepository, userSubscriptionRepository, userGroupRateRepository, gatewayCache, configConfig, schedulerSnapshotService, concurrencyService, billingService, rateLimitService, billingCacheService, httpUpstream, deferredService, openAITokenProvider, settingService, modelRegistryService, modelCatalogService, channelService)
	accountTestService := service.ProvideAccountTestService(accountRepository, accountModelImportService, claudeTokenProvider, openAITokenProvider, geminiTokenProvider, antigravityGatewayService, gatewayService, grokGatewayService, openAIGatewayService, geminiMessagesCompatService, userRepository, apiKeyRepository, usageLogRepository, httpUpstream, configConfig, tlsFingerprintProfileService)
	crsSyncService := service.NewCRSSyncService(accountRepository, proxyRepository, oAuthService, openAIOAuthService, geminiOAuthService, configConfig)
	accountModelDiagnosticsService := service.ProvideAccountModelDiagnosticsService(accountRepository, apiKeyRepository, groupRepository, accountModelImportService)
	opsRepository := repository.NewOpsRepository(db)
	opsSystemLogSink := service.ProvideOpsSystemLogSink(opsRepository)
	opsService := service.NewOpsService(opsRepository, settingRepository, configConfig, accountRepository, userRepository, concurrencyService, gatewayService, openAIGatewayService, geminiMessagesCompatService, antigravityGatewayService, opsSystemLogSink)
	accountHandler := handler.ProvideAdminAccountHandler(adminService, oAuthService, openAIOAuthService, kiroOAuthService, geminiOAuthService, antigravityOAuthService, rateLimitService, accountUsageService, accountTestService, concurrencyService, crsSyncService, sessionLimitCache, rpmCache, compositeTokenCacheInvalidator, accountModelImportService, accountModelDiagnosticsService, modelRegistryService, settingService, opsService)
	affiliateHandler := admin.NewAffiliateHandler(affiliateService)
	emailTemplateHandler := admin.NewEmailTemplateHandler(emailTemplateService, emailService, settingService)
	adminAnnouncementHandler := admin.NewAnnouncementHandler(announcementService)
	dataManagementService := service.NewDataManagementService()
	dataManagementHandler := admin.NewDataManagementHandler(dataManagementService)
	backupObjectStoreFactory := repository.NewS3BackupStoreFactory()
	dbDumper := repository.NewPgDumper(configConfig)
	backupService := service.ProvideBackupService(settingRepository, configConfig, secretEncryptor, backupObjectStoreFactory, dbDumper)
	backupHandler := admin.NewBackupHandler(backupService, userService)
	oAuthHandler := admin.NewOAuthHandler(oAuthService)
	openAIOAuthHandler := handler.ProvideOpenAIOAuthHandler(openAIOAuthService, adminService)
	kiroOAuthHandler := admin.NewKiroOAuthHandler(kiroOAuthService, adminService)
	geminiOAuthHandler := admin.NewGeminiOAuthHandler(geminiOAuthService)
	antigravityOAuthHandler := admin.NewAntigravityOAuthHandler(antigravityOAuthService)
	proxyHandler := admin.NewProxyHandler(adminService)
	adminRedeemHandler := admin.NewRedeemHandler(adminService, redeemService)
	promoHandler := admin.NewPromoHandler(promoService)
	telegramNotifierService := service.NewTelegramNotifierService(settingService)
	settingHandler := handler.ProvideAdminSettingHandler(settingService, emailService, telegramNotifierService, turnstileService, opsService, emailTemplateService)
	opsHandler := admin.NewOpsHandler(opsService)
	updateCache := repository.NewUpdateCache(redisClient)
	gitHubReleaseClient := repository.ProvideGitHubReleaseClient(configConfig)
	serviceBuildInfo := provideServiceBuildInfo(buildInfo)
	updateService := service.ProvideUpdateService(updateCache, gitHubReleaseClient, serviceBuildInfo)
	idempotencyRepository := repository.NewIdempotencyRepository(client, db)
	systemOperationLockService := service.ProvideSystemOperationLockService(idempotencyRepository, configConfig)
	systemHandler := handler.ProvideSystemHandler(updateService, systemOperationLockService)
	adminSubscriptionHandler := admin.NewSubscriptionHandler(subscriptionService)
	usageCleanupRepository := repository.NewUsageCleanupRepository(client, db)
	usageCleanupService := service.ProvideUsageCleanupService(usageCleanupRepository, timingWheelService, dashboardAggregationService, configConfig)
	usageRepairRepository := repository.NewUsageRepairRepository(db)
	usageRepairService := service.ProvideUsageRepairService(usageRepairRepository, timingWheelService)
	adminUsageHandler := admin.NewUsageHandler(usageService, apiKeyService, adminService, usageCleanupService, usageRepairService)
	userAttributeHandler := admin.NewUserAttributeHandler(userAttributeService)
	errorPassthroughRepository := repository.NewErrorPassthroughRepository(client)
	errorPassthroughCache := repository.NewErrorPassthroughCache(redisClient)
	errorPassthroughService := service.NewErrorPassthroughService(errorPassthroughRepository, errorPassthroughCache)
	errorPassthroughHandler := admin.NewErrorPassthroughHandler(errorPassthroughService)
	adminAPIKeyHandler := admin.NewAdminAPIKeyHandler(adminService)
	modelDebugService := service.NewModelDebugService(apiKeyService, opsService, configConfig)
	modelCatalogHandler := handler.ProvideAdminModelCatalogHandler(modelCatalogService, userService, modelDebugService)
	modelRegistryHandler := admin.NewModelRegistryHandler(modelRegistryService)
	scheduledTestPlanRepository := repository.NewScheduledTestPlanRepository(db)
	scheduledTestResultRepository := repository.NewScheduledTestResultRepository(db)
	scheduledTestService := service.ProvideScheduledTestService(scheduledTestPlanRepository, scheduledTestResultRepository)
	scheduledTestHandler := admin.NewScheduledTestHandler(scheduledTestService)
	tlsFingerprintProfileHandler := admin.NewTLSFingerprintProfileHandler(tlsFingerprintProfileService)
	paymentRepository := repository.NewPaymentRepository(db)
	httpAirwallexClient := service.NewHTTPAirwallexClient()
	paymentService := service.ProvidePaymentService(paymentRepository, settingService, httpAirwallexClient, subscriptionService, affiliateService, emailService, emailTemplateService, userRepository, billingCacheService, apiKeyAuthCacheInvalidator)
	adminPaymentHandler := handler.NewAdminPaymentHandler(paymentService)
	adminHandlers := handler.ProvideAdminHandlers(dashboardHandler, adminUserHandler, contentModerationAuditHandler, groupHandler, channelHandler, adminChannelMonitorHandler, channelMonitorTemplateHandler, accountHandler, affiliateHandler, emailTemplateHandler, adminAnnouncementHandler, dataManagementHandler, backupHandler, oAuthHandler, openAIOAuthHandler, kiroOAuthHandler, geminiOAuthHandler, antigravityOAuthHandler, proxyHandler, adminRedeemHandler, promoHandler, settingHandler, opsHandler, systemHandler, adminSubscriptionHandler, adminUsageHandler, userAttributeHandler, errorPassthroughHandler, adminAPIKeyHandler, modelCatalogHandler, modelRegistryHandler, scheduledTestHandler, tlsFingerprintProfileHandler, adminPaymentHandler)
	geminiNativeGatewayService := service.ProvideGeminiNativeGatewayService(geminiMessagesCompatService)
	geminiCompatGatewayService := service.ProvideGeminiCompatGatewayService(geminiMessagesCompatService)
	geminiLiveGatewayService := service.ProvideGeminiLiveGatewayService(geminiMessagesCompatService)
	geminiInteractionsGatewayService := service.ProvideGeminiInteractionsGatewayService(geminiMessagesCompatService)
	usageRecordWorkerPool := service.NewUsageRecordWorkerPool(configConfig)
	userMsgQueueCache := repository.NewUserMsgQueueCache(redisClient)
	userMessageQueueService := service.ProvideUserMessageQueueService(userMsgQueueCache, rpmCache, configConfig)
	gatewayHandler := handler.ProvideGatewayHandler(gatewayService, geminiNativeGatewayService, geminiCompatGatewayService, geminiLiveGatewayService, geminiInteractionsGatewayService, antigravityGatewayService, userService, concurrencyService, billingCacheService, usageService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, userMessageQueueService, configConfig, settingService, modelRegistryService, contentModerationService)
	openAIGatewayHandler := handler.ProvideOpenAIGatewayHandler(openAIGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, errorPassthroughService, configConfig, settingService, contentModerationService)
	grokGatewayHandler := handler.ProvideGrokGatewayHandler(gatewayService, grokGatewayService, concurrencyService, billingCacheService, apiKeyService, usageRecordWorkerPool, configConfig, settingService)
	documentAIJobRepository := repository.NewDocumentAIJobRepository(db)
	documentAIService := service.ProvideDocumentAIService(documentAIJobRepository, accountRepository, httpUpstream, tlsFingerprintProfileService, timingWheelService, settingService, configConfig)
	documentAIHandler := handler.ProvideDocumentAIHandler(documentAIService, billingCacheService, apiKeyService, subscriptionService)
	handlerSettingHandler := handler.ProvideSettingHandler(settingService, buildInfo)
	totpHandler := handler.NewTotpHandler(totpService)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	idempotencyCoordinator := service.ProvideIdempotencyCoordinator(idempotencyRepository, configConfig)
	idempotencyCleanupService := service.ProvideIdempotencyCleanupService(idempotencyRepository, configConfig)
	handlers := handler.ProvideHandlers(authHandler, userHandler, metaHandler, apiKeyHandler, availableChannelHandler, channelMonitorHandler, usageHandler, redeemHandler, subscriptionHandler, announcementHandler, adminHandlers, gatewayHandler, openAIGatewayHandler, grokGatewayHandler, documentAIHandler, handlerSettingHandler, totpHandler, paymentHandler, opsService, idempotencyCoordinator, idempotencyCleanupService)
	jwtAuthMiddleware := middleware.NewJWTAuthMiddleware(authService, userService)
	adminAuthMiddleware := middleware.NewAdminAuthMiddleware(authService, userService, settingService)
	apiKeyAuthMiddleware := middleware.NewAPIKeyAuthMiddleware(apiKeyService, subscriptionService, configConfig)
	engine := server.ProvideRouter(configConfig, handlers, jwtAuthMiddleware, adminAuthMiddleware, apiKeyAuthMiddleware, apiKeyService, subscriptionService, opsService, settingService, redisClient)
	httpServer := server.ProvideHTTPServer(configConfig, engine)
	opsMetricsCollector := service.ProvideOpsMetricsCollector(opsRepository, settingRepository, accountRepository, concurrencyService, db, redisClient, configConfig)
	opsAggregationService := service.ProvideOpsAggregationService(opsRepository, settingRepository, db, redisClient, configConfig)
	opsAlertEvaluatorService := service.ProvideOpsAlertEvaluatorService(opsService, opsRepository, emailService, redisClient, configConfig)
	opsCleanupService := service.ProvideOpsCleanupService(opsRepository, settingRepository, db, redisClient, configConfig, settingService, opsService)
	opsScheduledReportService := service.ProvideOpsScheduledReportService(opsService, userService, emailService, redisClient, configConfig)
	googleBatchArchivePollerService := service.ProvideGoogleBatchArchivePollerService(googleBatchArchiveJobRepository, geminiMessagesCompatService, settingService)
	googleBatchArchivePrefetchService := service.ProvideGoogleBatchArchivePrefetchService(googleBatchArchiveJobRepository, googleBatchArchiveObjectRepository, geminiMessagesCompatService, settingService)
	googleBatchArchiveCleanupService := service.ProvideGoogleBatchArchiveCleanupService(googleBatchArchiveJobRepository, googleBatchArchiveObjectRepository, geminiMessagesCompatService, settingService)
	tokenRefreshService := service.ProvideTokenRefreshService(accountRepository, oAuthService, kiroOAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, compositeTokenCacheInvalidator, schedulerCache, configConfig, tempUnschedCache, privacyClientFactory, proxyRepository, oAuthRefreshAPI)
	openAIGPT55WhitelistBackfillService := service.ProvideOpenAIGPT55WhitelistBackfillService(settingRepository, accountRepository)
	periodicJobLeaderGate := repository.NewPeriodicJobLeaderGate(redisClient, configConfig)
	accountExpiryService := service.ProvideAccountExpiryService(accountRepository, accountTestService, periodicJobLeaderGate)
	proxyExpiryService := service.ProvideProxyExpiryService(proxyRepository, accountRepository, periodicJobLeaderGate)
	accountDaily5HTriggerService := service.ProvideAccountDaily5HTriggerService(accountRepository, accountTestService, settingService, modelRegistryService, periodicJobLeaderGate)
	accountBlacklistCleanupService := service.ProvideAccountBlacklistCleanupService(accountRepository, periodicJobLeaderGate)
	accountRateLimitRecoveryProbeService := service.ProvideAccountRateLimitRecoveryProbeService(accountRepository, accountTestService, rateLimitService, periodicJobLeaderGate)
	subscriptionExpiryService := service.ProvideSubscriptionExpiryService(userSubscriptionRepository, emailService, emailTemplateService, userRepository, settingService, periodicJobLeaderGate)
	scheduledTestRunnerService := service.ProvideScheduledTestRunnerService(scheduledTestPlanRepository, scheduledTestService, accountTestService, rateLimitService, accountRepository, telegramNotifierService, emailService, emailTemplateService, opsService, configConfig)
	channelMonitorAggregationRepository := repository.NewChannelMonitorAggregationRepository(db)
	channelMonitorRunnerService := service.ProvideChannelMonitorRunnerService(db, channelMonitorRepository, channelMonitorHistoryRepository, channelMonitorRollupRepository, channelMonitorAggregationRepository, settingService, secretEncryptor, configConfig)
	publicModelCatalogRevalidationRunner := service.ProvidePublicModelCatalogRevalidationRunner(modelCatalogService, gatewayService)
	v := provideCleanup(client, redisClient, opsMetricsCollector, opsAggregationService, opsAlertEvaluatorService, opsCleanupService, opsScheduledReportService, opsSystemLogSink, googleBatchArchivePollerService, googleBatchArchivePrefetchService, googleBatchArchiveCleanupService, schedulerSnapshotService, tokenRefreshService, openAIGPT55WhitelistBackfillService, accountExpiryService, proxyExpiryService, accountDaily5HTriggerService, accountBlacklistCleanupService, accountRateLimitRecoveryProbeService, subscriptionExpiryService, usageCleanupService, usageRepairService, documentAIService, idempotencyCleanupService, pricingService, emailQueueService, billingCacheService, usageRecordWorkerPool, subscriptionService, oAuthService, openAIOAuthService, geminiOAuthService, antigravityOAuthService, openAIGatewayService, scheduledTestRunnerService, channelMonitorRunnerService, publicModelCatalogRevalidationRunner, backupService)
	application := &Application{
		Server:  httpServer,
		Cleanup: v,
	}
	return application, nil
}

// wire.go:

type Application struct {
	Server  *http.Server
	Cleanup func()
}

func provideServiceBuildInfo(buildInfo handler.BuildInfo) service.BuildInfo {
	return service.BuildInfo{
		Version:   buildInfo.Version,
		BuildType: buildInfo.BuildType,
	}
}

func provideCleanup(
	entClient *ent.Client,
	rdb *redis.Client,
	opsMetricsCollector *service.OpsMetricsCollector,
	opsAggregation *service.OpsAggregationService,
	opsAlertEvaluator *service.OpsAlertEvaluatorService,
	opsCleanup *service.OpsCleanupService,
	opsScheduledReport *service.OpsScheduledReportService,
	opsSystemLogSink *service.OpsSystemLogSink,
	googleBatchArchivePoller *service.GoogleBatchArchivePollerService,
	googleBatchArchivePrefetch *service.GoogleBatchArchivePrefetchService,
	googleBatchArchiveCleanup *service.GoogleBatchArchiveCleanupService,
	schedulerSnapshot *service.SchedulerSnapshotService,
	tokenRefresh *service.TokenRefreshService,
	openAIGPT55WhitelistBackfill *service.OpenAIGPT55WhitelistBackfillService,
	accountExpiry *service.AccountExpiryService,
	proxyExpiry *service.ProxyExpiryService,
	accountDaily5HTrigger *service.AccountDaily5HTriggerService,
	accountBlacklistCleanup *service.AccountBlacklistCleanupService,
	accountRateLimitRecoveryProbe *service.AccountRateLimitRecoveryProbeService,
	subscriptionExpiry *service.SubscriptionExpiryService,
	usageCleanup *service.UsageCleanupService,
	usageRepair *service.UsageRepairService,
	documentAI *service.DocumentAIService,
	idempotencyCleanup *service.IdempotencyCleanupService,
	pricing *service.PricingService,
	emailQueue *service.EmailQueueService,
	billingCache *service.BillingCacheService,
	usageRecordWorkerPool *service.UsageRecordWorkerPool,
	subscriptionService *service.SubscriptionService,
	oauth *service.OAuthService,
	openaiOAuth *service.OpenAIOAuthService,
	geminiOAuth *service.GeminiOAuthService,
	antigravityOAuth *service.AntigravityOAuthService,
	openAIGateway *service.OpenAIGatewayService,
	scheduledTestRunner *service.ScheduledTestRunnerService,
	channelMonitorRunner *service.ChannelMonitorRunnerService,
	publicModelCatalogRevalidationRunner *service.PublicModelCatalogRevalidationRunner,
	backupSvc *service.BackupService,
) func() {
	return func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		type cleanupStep struct {
			name string
			fn   func() error
		}

		parallelSteps := []cleanupStep{
			{"OpsScheduledReportService", func() error {
				if opsScheduledReport != nil {
					opsScheduledReport.Stop()
				}
				return nil
			}},
			{"OpsCleanupService", func() error {
				if opsCleanup != nil {
					opsCleanup.Stop()
				}
				return nil
			}},
			{"OpsSystemLogSink", func() error {
				if opsSystemLogSink != nil {
					opsSystemLogSink.Stop()
				}
				return nil
			}},
			{"GoogleBatchArchivePollerService", func() error {
				if googleBatchArchivePoller != nil {
					googleBatchArchivePoller.Stop()
				}
				return nil
			}},
			{"GoogleBatchArchivePrefetchService", func() error {
				if googleBatchArchivePrefetch != nil {
					googleBatchArchivePrefetch.Stop()
				}
				return nil
			}},
			{"GoogleBatchArchiveCleanupService", func() error {
				if googleBatchArchiveCleanup != nil {
					googleBatchArchiveCleanup.Stop()
				}
				return nil
			}},
			{"OpsAlertEvaluatorService", func() error {
				if opsAlertEvaluator != nil {
					opsAlertEvaluator.Stop()
				}
				return nil
			}},
			{"OpsAggregationService", func() error {
				if opsAggregation != nil {
					opsAggregation.Stop()
				}
				return nil
			}},
			{"OpsMetricsCollector", func() error {
				if opsMetricsCollector != nil {
					opsMetricsCollector.Stop()
				}
				return nil
			}},
			{"SchedulerSnapshotService", func() error {
				if schedulerSnapshot != nil {
					schedulerSnapshot.Stop()
				}
				return nil
			}},
			{"UsageCleanupService", func() error {
				if usageCleanup != nil {
					usageCleanup.Stop()
				}
				return nil
			}},
			{"UsageRepairService", func() error {
				if usageRepair != nil {
					usageRepair.Stop()
				}
				return nil
			}},
			{"DocumentAIService", func() error {
				if documentAI != nil {
					documentAI.Stop()
				}
				return nil
			}},
			{"IdempotencyCleanupService", func() error {
				if idempotencyCleanup != nil {
					idempotencyCleanup.Stop()
				}
				return nil
			}},
			{"TokenRefreshService", func() error {
				tokenRefresh.Stop()
				return nil
			}},
			{"OpenAIGPT55WhitelistBackfillService", func() error {
				if openAIGPT55WhitelistBackfill != nil {
					openAIGPT55WhitelistBackfill.Stop()
				}
				return nil
			}},
			{"AccountExpiryService", func() error {
				accountExpiry.Stop()
				return nil
			}},
			{"ProxyExpiryService", func() error {
				if proxyExpiry != nil {
					proxyExpiry.Stop()
				}
				return nil
			}},
			{"AccountDaily5HTriggerService", func() error {
				if accountDaily5HTrigger != nil {
					accountDaily5HTrigger.Stop()
				}
				return nil
			}},
			{"AccountBlacklistCleanupService", func() error {
				if accountBlacklistCleanup != nil {
					accountBlacklistCleanup.Stop()
				}
				return nil
			}},
			{"AccountRateLimitRecoveryProbeService", func() error {
				if accountRateLimitRecoveryProbe != nil {
					accountRateLimitRecoveryProbe.Stop()
				}
				return nil
			}},
			{"SubscriptionExpiryService", func() error {
				subscriptionExpiry.Stop()
				return nil
			}},
			{"SubscriptionService", func() error {
				if subscriptionService != nil {
					subscriptionService.Stop()
				}
				return nil
			}},
			{"PricingService", func() error {
				pricing.Stop()
				return nil
			}},
			{"EmailQueueService", func() error {
				emailQueue.Stop()
				return nil
			}},
			{"BillingCacheService", func() error {
				billingCache.Stop()
				return nil
			}},
			{"UsageRecordWorkerPool", func() error {
				if usageRecordWorkerPool != nil {
					usageRecordWorkerPool.Stop()
				}
				return nil
			}},
			{"OAuthService", func() error {
				oauth.Stop()
				return nil
			}},
			{"OpenAIOAuthService", func() error {
				openaiOAuth.Stop()
				return nil
			}},
			{"GeminiOAuthService", func() error {
				geminiOAuth.Stop()
				return nil
			}},
			{"AntigravityOAuthService", func() error {
				antigravityOAuth.Stop()
				return nil
			}},
			{"OpenAIWSPool", func() error {
				if openAIGateway != nil {
					openAIGateway.CloseOpenAIWSPool()
				}
				return nil
			}},
			{"ScheduledTestRunnerService", func() error {
				if scheduledTestRunner != nil {
					scheduledTestRunner.Stop()
				}
				return nil
			}},
			{"ChannelMonitorRunnerService", func() error {
				if channelMonitorRunner != nil {
					channelMonitorRunner.Stop()
				}
				return nil
			}},
			{"PublicModelCatalogRevalidationRunner", func() error {
				if publicModelCatalogRevalidationRunner != nil {
					publicModelCatalogRevalidationRunner.Stop()
				}
				return nil
			}},
			{"BackupService", func() error {
				if backupSvc != nil {
					backupSvc.Stop()
				}
				return nil
			}},
		}

		infraSteps := []cleanupStep{
			{"Redis", func() error {
				if rdb == nil {
					return nil
				}
				return rdb.Close()
			}},
			{"Ent", func() error {
				if entClient == nil {
					return nil
				}
				return entClient.Close()
			}},
		}

		runParallel := func(steps []cleanupStep) {
			var wg sync.WaitGroup
			for i := range steps {
				step := steps[i]
				wg.Add(1)
				go func() {
					defer wg.Done()
					if err := step.fn(); err != nil {
						log.Printf("[Cleanup] %s failed: %v", step.name, err)
						return
					}
					log.Printf("[Cleanup] %s succeeded", step.name)
				}()
			}
			wg.Wait()
		}

		runSequential := func(steps []cleanupStep) {
			for i := range steps {
				step := steps[i]
				if err := step.fn(); err != nil {
					log.Printf("[Cleanup] %s failed: %v", step.name, err)
					continue
				}
				log.Printf("[Cleanup] %s succeeded", step.name)
			}
		}

		runParallel(parallelSteps)
		runSequential(infraSteps)

		select {
		case <-ctx.Done():
			log.Printf("[Cleanup] Warning: cleanup timed out after 10 seconds")
		default:
			log.Printf("[Cleanup] All cleanup steps completed")
		}
	}
}
