// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// CompositeModelRouteCreate is the builder for creating a CompositeModelRoute entity.
type CompositeModelRouteCreate struct {
	config
	mutation *CompositeModelRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CompositeModelRouteCreate) SetCreatedAt(v time.Time) *CompositeModelRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CompositeModelRouteCreate) SetNillableCreatedAt(v *time.Time) *CompositeModelRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CompositeModelRouteCreate) SetUpdatedAt(v time.Time) *CompositeModelRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CompositeModelRouteCreate) SetNillableUpdatedAt(v *time.Time) *CompositeModelRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetParentGroupID sets the "parent_group_id" field.
func (_c *CompositeModelRouteCreate) SetParentGroupID(v int64) *CompositeModelRouteCreate {
	_c.mutation.SetParentGroupID(v)
	return _c
}

// SetDisplayModelID sets the "display_model_id" field.
func (_c *CompositeModelRouteCreate) SetDisplayModelID(v string) *CompositeModelRouteCreate {
	_c.mutation.SetDisplayModelID(v)
	return _c
}

// SetTargetGroupID sets the "target_group_id" field.
func (_c *CompositeModelRouteCreate) SetTargetGroupID(v int64) *CompositeModelRouteCreate {
	_c.mutation.SetTargetGroupID(v)
	return _c
}

// SetTargetModelID sets the "target_model_id" field.
func (_c *CompositeModelRouteCreate) SetTargetModelID(v string) *CompositeModelRouteCreate {
	_c.mutation.SetTargetModelID(v)
	return _c
}

// SetNillableTargetModelID sets the "target_model_id" field if the given value is not nil.
func (_c *CompositeModelRouteCreate) SetNillableTargetModelID(v *string) *CompositeModelRouteCreate {
	if v != nil {
		_c.SetTargetModelID(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *CompositeModelRouteCreate) SetPriority(v int) *CompositeModelRouteCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *CompositeModelRouteCreate) SetNillablePriority(v *int) *CompositeModelRouteCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CompositeModelRouteCreate) SetEnabled(v bool) *CompositeModelRouteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CompositeModelRouteCreate) SetNillableEnabled(v *bool) *CompositeModelRouteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *CompositeModelRouteCreate) SetNotes(v string) *CompositeModelRouteCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *CompositeModelRouteCreate) SetNillableNotes(v *string) *CompositeModelRouteCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetParentGroup sets the "parent_group" edge to the Group entity.
func (_c *CompositeModelRouteCreate) SetParentGroup(v *Group) *CompositeModelRouteCreate {
	return _c.SetParentGroupID(v.ID)
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_c *CompositeModelRouteCreate) SetTargetGroup(v *Group) *CompositeModelRouteCreate {
	return _c.SetTargetGroupID(v.ID)
}

// Mutation returns the CompositeModelRouteMutation object of the builder.
func (_c *CompositeModelRouteCreate) Mutation() *CompositeModelRouteMutation {
	return _c.mutation
}

// Save creates the CompositeModelRoute in the database.
func (_c *CompositeModelRouteCreate) Save(ctx context.Context) (*CompositeModelRoute, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CompositeModelRouteCreate) SaveX(ctx context.Context) *CompositeModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompositeModelRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompositeModelRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CompositeModelRouteCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := compositemodelroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := compositemodelroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TargetModelID(); !ok {
		v := compositemodelroute.DefaultTargetModelID
		_c.mutation.SetTargetModelID(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := compositemodelroute.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := compositemodelroute.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := compositemodelroute.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CompositeModelRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CompositeModelRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CompositeModelRoute.updated_at"`)}
	}
	if _, ok := _c.mutation.ParentGroupID(); !ok {
		return &ValidationError{Name: "parent_group_id", err: errors.New(`ent: missing required field "CompositeModelRoute.parent_group_id"`)}
	}
	if _, ok := _c.mutation.DisplayModelID(); !ok {
		return &ValidationError{Name: "display_model_id", err: errors.New(`ent: missing required field "CompositeModelRoute.display_model_id"`)}
	}
	if v, ok := _c.mutation.DisplayModelID(); ok {
		if err := compositemodelroute.DisplayModelIDValidator(v); err != nil {
			return &ValidationError{Name: "display_model_id", err: fmt.Errorf(`ent: validator failed for field "CompositeModelRoute.display_model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetGroupID(); !ok {
		return &ValidationError{Name: "target_group_id", err: errors.New(`ent: missing required field "CompositeModelRoute.target_group_id"`)}
	}
	if _, ok := _c.mutation.TargetModelID(); !ok {
		return &ValidationError{Name: "target_model_id", err: errors.New(`ent: missing required field "CompositeModelRoute.target_model_id"`)}
	}
	if v, ok := _c.mutation.TargetModelID(); ok {
		if err := compositemodelroute.TargetModelIDValidator(v); err != nil {
			return &ValidationError{Name: "target_model_id", err: fmt.Errorf(`ent: validator failed for field "CompositeModelRoute.target_model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "CompositeModelRoute.priority"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CompositeModelRoute.enabled"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "CompositeModelRoute.notes"`)}
	}
	if len(_c.mutation.ParentGroupIDs()) == 0 {
		return &ValidationError{Name: "parent_group", err: errors.New(`ent: missing required edge "CompositeModelRoute.parent_group"`)}
	}
	if len(_c.mutation.TargetGroupIDs()) == 0 {
		return &ValidationError{Name: "target_group", err: errors.New(`ent: missing required edge "CompositeModelRoute.target_group"`)}
	}
	return nil
}

func (_c *CompositeModelRouteCreate) sqlSave(ctx context.Context) (*CompositeModelRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CompositeModelRouteCreate) createSpec() (*CompositeModelRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &CompositeModelRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(compositemodelroute.Table, sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(compositemodelroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(compositemodelroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DisplayModelID(); ok {
		_spec.SetField(compositemodelroute.FieldDisplayModelID, field.TypeString, value)
		_node.DisplayModelID = value
	}
	if value, ok := _c.mutation.TargetModelID(); ok {
		_spec.SetField(compositemodelroute.FieldTargetModelID, field.TypeString, value)
		_node.TargetModelID = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(compositemodelroute.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(compositemodelroute.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(compositemodelroute.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if nodes := _c.mutation.ParentGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.ParentGroupTable,
			Columns: []string{compositemodelroute.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.TargetGroupTable,
			Columns: []string{compositemodelroute.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CompositeModelRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CompositeModelRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CompositeModelRouteCreate) OnConflict(opts ...sql.ConflictOption) *CompositeModelRouteUpsertOne {
	_c.conflict = opts
	return &CompositeModelRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CompositeModelRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CompositeModelRouteCreate) OnConflictColumns(columns ...string) *CompositeModelRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CompositeModelRouteUpsertOne{
		create: _c,
	}
}

type (
	// CompositeModelRouteUpsertOne is the builder for "upsert"-ing
	//  one CompositeModelRoute node.
	CompositeModelRouteUpsertOne struct {
		create *CompositeModelRouteCreate
	}

	// CompositeModelRouteUpsert is the "OnConflict" setter.
	CompositeModelRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CompositeModelRouteUpsert) SetUpdatedAt(v time.Time) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateUpdatedAt() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldUpdatedAt)
	return u
}

// SetParentGroupID sets the "parent_group_id" field.
func (u *CompositeModelRouteUpsert) SetParentGroupID(v int64) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldParentGroupID, v)
	return u
}

// UpdateParentGroupID sets the "parent_group_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateParentGroupID() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldParentGroupID)
	return u
}

// SetDisplayModelID sets the "display_model_id" field.
func (u *CompositeModelRouteUpsert) SetDisplayModelID(v string) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldDisplayModelID, v)
	return u
}

// UpdateDisplayModelID sets the "display_model_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateDisplayModelID() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldDisplayModelID)
	return u
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *CompositeModelRouteUpsert) SetTargetGroupID(v int64) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldTargetGroupID, v)
	return u
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateTargetGroupID() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldTargetGroupID)
	return u
}

// SetTargetModelID sets the "target_model_id" field.
func (u *CompositeModelRouteUpsert) SetTargetModelID(v string) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldTargetModelID, v)
	return u
}

// UpdateTargetModelID sets the "target_model_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateTargetModelID() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldTargetModelID)
	return u
}

// SetPriority sets the "priority" field.
func (u *CompositeModelRouteUpsert) SetPriority(v int) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdatePriority() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *CompositeModelRouteUpsert) AddPriority(v int) *CompositeModelRouteUpsert {
	u.Add(compositemodelroute.FieldPriority, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CompositeModelRouteUpsert) SetEnabled(v bool) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateEnabled() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldEnabled)
	return u
}

// SetNotes sets the "notes" field.
func (u *CompositeModelRouteUpsert) SetNotes(v string) *CompositeModelRouteUpsert {
	u.Set(compositemodelroute.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CompositeModelRouteUpsert) UpdateNotes() *CompositeModelRouteUpsert {
	u.SetExcluded(compositemodelroute.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CompositeModelRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CompositeModelRouteUpsertOne) UpdateNewValues() *CompositeModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(compositemodelroute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CompositeModelRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CompositeModelRouteUpsertOne) Ignore() *CompositeModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CompositeModelRouteUpsertOne) DoNothing() *CompositeModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CompositeModelRouteCreate.OnConflict
// documentation for more info.
func (u *CompositeModelRouteUpsertOne) Update(set func(*CompositeModelRouteUpsert)) *CompositeModelRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CompositeModelRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CompositeModelRouteUpsertOne) SetUpdatedAt(v time.Time) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateUpdatedAt() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetParentGroupID sets the "parent_group_id" field.
func (u *CompositeModelRouteUpsertOne) SetParentGroupID(v int64) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetParentGroupID(v)
	})
}

// UpdateParentGroupID sets the "parent_group_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateParentGroupID() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateParentGroupID()
	})
}

// SetDisplayModelID sets the "display_model_id" field.
func (u *CompositeModelRouteUpsertOne) SetDisplayModelID(v string) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetDisplayModelID(v)
	})
}

// UpdateDisplayModelID sets the "display_model_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateDisplayModelID() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateDisplayModelID()
	})
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *CompositeModelRouteUpsertOne) SetTargetGroupID(v int64) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetTargetGroupID(v)
	})
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateTargetGroupID() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateTargetGroupID()
	})
}

// SetTargetModelID sets the "target_model_id" field.
func (u *CompositeModelRouteUpsertOne) SetTargetModelID(v string) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetTargetModelID(v)
	})
}

// UpdateTargetModelID sets the "target_model_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateTargetModelID() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateTargetModelID()
	})
}

// SetPriority sets the "priority" field.
func (u *CompositeModelRouteUpsertOne) SetPriority(v int) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *CompositeModelRouteUpsertOne) AddPriority(v int) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdatePriority() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CompositeModelRouteUpsertOne) SetEnabled(v bool) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateEnabled() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateEnabled()
	})
}

// SetNotes sets the "notes" field.
func (u *CompositeModelRouteUpsertOne) SetNotes(v string) *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertOne) UpdateNotes() *CompositeModelRouteUpsertOne {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *CompositeModelRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CompositeModelRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CompositeModelRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CompositeModelRouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CompositeModelRouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CompositeModelRouteCreateBulk is the builder for creating many CompositeModelRoute entities in bulk.
type CompositeModelRouteCreateBulk struct {
	config
	err      error
	builders []*CompositeModelRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the CompositeModelRoute entities in the database.
func (_c *CompositeModelRouteCreateBulk) Save(ctx context.Context) ([]*CompositeModelRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CompositeModelRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CompositeModelRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CompositeModelRouteCreateBulk) SaveX(ctx context.Context) []*CompositeModelRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CompositeModelRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CompositeModelRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CompositeModelRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CompositeModelRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CompositeModelRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *CompositeModelRouteUpsertBulk {
	_c.conflict = opts
	return &CompositeModelRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CompositeModelRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CompositeModelRouteCreateBulk) OnConflictColumns(columns ...string) *CompositeModelRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CompositeModelRouteUpsertBulk{
		create: _c,
	}
}

// CompositeModelRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of CompositeModelRoute nodes.
type CompositeModelRouteUpsertBulk struct {
	create *CompositeModelRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CompositeModelRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CompositeModelRouteUpsertBulk) UpdateNewValues() *CompositeModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(compositemodelroute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CompositeModelRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CompositeModelRouteUpsertBulk) Ignore() *CompositeModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CompositeModelRouteUpsertBulk) DoNothing() *CompositeModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CompositeModelRouteCreateBulk.OnConflict
// documentation for more info.
func (u *CompositeModelRouteUpsertBulk) Update(set func(*CompositeModelRouteUpsert)) *CompositeModelRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CompositeModelRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CompositeModelRouteUpsertBulk) SetUpdatedAt(v time.Time) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateUpdatedAt() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetParentGroupID sets the "parent_group_id" field.
func (u *CompositeModelRouteUpsertBulk) SetParentGroupID(v int64) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetParentGroupID(v)
	})
}

// UpdateParentGroupID sets the "parent_group_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateParentGroupID() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateParentGroupID()
	})
}

// SetDisplayModelID sets the "display_model_id" field.
func (u *CompositeModelRouteUpsertBulk) SetDisplayModelID(v string) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetDisplayModelID(v)
	})
}

// UpdateDisplayModelID sets the "display_model_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateDisplayModelID() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateDisplayModelID()
	})
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *CompositeModelRouteUpsertBulk) SetTargetGroupID(v int64) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetTargetGroupID(v)
	})
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateTargetGroupID() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateTargetGroupID()
	})
}

// SetTargetModelID sets the "target_model_id" field.
func (u *CompositeModelRouteUpsertBulk) SetTargetModelID(v string) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetTargetModelID(v)
	})
}

// UpdateTargetModelID sets the "target_model_id" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateTargetModelID() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateTargetModelID()
	})
}

// SetPriority sets the "priority" field.
func (u *CompositeModelRouteUpsertBulk) SetPriority(v int) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *CompositeModelRouteUpsertBulk) AddPriority(v int) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdatePriority() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CompositeModelRouteUpsertBulk) SetEnabled(v bool) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateEnabled() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateEnabled()
	})
}

// SetNotes sets the "notes" field.
func (u *CompositeModelRouteUpsertBulk) SetNotes(v string) *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CompositeModelRouteUpsertBulk) UpdateNotes() *CompositeModelRouteUpsertBulk {
	return u.Update(func(s *CompositeModelRouteUpsert) {
		s.UpdateNotes()
	})
}

// Exec executes the query.
func (u *CompositeModelRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CompositeModelRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CompositeModelRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CompositeModelRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
