// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CompositeModelRouteUpdate is the builder for updating CompositeModelRoute entities.
type CompositeModelRouteUpdate struct {
	config
	hooks    []Hook
	mutation *CompositeModelRouteMutation
}

// Where appends a list predicates to the CompositeModelRouteUpdate builder.
func (_u *CompositeModelRouteUpdate) Where(ps ...predicate.CompositeModelRoute) *CompositeModelRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompositeModelRouteUpdate) SetUpdatedAt(v time.Time) *CompositeModelRouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentGroupID sets the "parent_group_id" field.
func (_u *CompositeModelRouteUpdate) SetParentGroupID(v int64) *CompositeModelRouteUpdate {
	_u.mutation.SetParentGroupID(v)
	return _u
}

// SetNillableParentGroupID sets the "parent_group_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillableParentGroupID(v *int64) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetParentGroupID(*v)
	}
	return _u
}

// SetDisplayModelID sets the "display_model_id" field.
func (_u *CompositeModelRouteUpdate) SetDisplayModelID(v string) *CompositeModelRouteUpdate {
	_u.mutation.SetDisplayModelID(v)
	return _u
}

// SetNillableDisplayModelID sets the "display_model_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillableDisplayModelID(v *string) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetDisplayModelID(*v)
	}
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *CompositeModelRouteUpdate) SetTargetGroupID(v int64) *CompositeModelRouteUpdate {
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillableTargetGroupID(v *int64) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// SetTargetModelID sets the "target_model_id" field.
func (_u *CompositeModelRouteUpdate) SetTargetModelID(v string) *CompositeModelRouteUpdate {
	_u.mutation.SetTargetModelID(v)
	return _u
}

// SetNillableTargetModelID sets the "target_model_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillableTargetModelID(v *string) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetTargetModelID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CompositeModelRouteUpdate) SetPriority(v int) *CompositeModelRouteUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillablePriority(v *int) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CompositeModelRouteUpdate) AddPriority(v int) *CompositeModelRouteUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CompositeModelRouteUpdate) SetEnabled(v bool) *CompositeModelRouteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillableEnabled(v *bool) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CompositeModelRouteUpdate) SetNotes(v string) *CompositeModelRouteUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CompositeModelRouteUpdate) SetNillableNotes(v *string) *CompositeModelRouteUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetParentGroup sets the "parent_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdate) SetParentGroup(v *Group) *CompositeModelRouteUpdate {
	return _u.SetParentGroupID(v.ID)
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdate) SetTargetGroup(v *Group) *CompositeModelRouteUpdate {
	return _u.SetTargetGroupID(v.ID)
}

// Mutation returns the CompositeModelRouteMutation object of the builder.
func (_u *CompositeModelRouteUpdate) Mutation() *CompositeModelRouteMutation {
	return _u.mutation
}

// ClearParentGroup clears the "parent_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdate) ClearParentGroup() *CompositeModelRouteUpdate {
	_u.mutation.ClearParentGroup()
	return _u
}

// ClearTargetGroup clears the "target_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdate) ClearTargetGroup() *CompositeModelRouteUpdate {
	_u.mutation.ClearTargetGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CompositeModelRouteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompositeModelRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CompositeModelRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompositeModelRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompositeModelRouteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := compositemodelroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompositeModelRouteUpdate) check() error {
	if v, ok := _u.mutation.DisplayModelID(); ok {
		if err := compositemodelroute.DisplayModelIDValidator(v); err != nil {
			return &ValidationError{Name: "display_model_id", err: fmt.Errorf(`ent: validator failed for field "CompositeModelRoute.display_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetModelID(); ok {
		if err := compositemodelroute.TargetModelIDValidator(v); err != nil {
			return &ValidationError{Name: "target_model_id", err: fmt.Errorf(`ent: validator failed for field "CompositeModelRoute.target_model_id": %w`, err)}
		}
	}
	if _u.mutation.ParentGroupCleared() && len(_u.mutation.ParentGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompositeModelRoute.parent_group"`)
	}
	if _u.mutation.TargetGroupCleared() && len(_u.mutation.TargetGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompositeModelRoute.target_group"`)
	}
	return nil
}

func (_u *CompositeModelRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(compositemodelroute.Table, compositemodelroute.Columns, sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(compositemodelroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModelID(); ok {
		_spec.SetField(compositemodelroute.FieldDisplayModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetModelID(); ok {
		_spec.SetField(compositemodelroute.FieldTargetModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(compositemodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(compositemodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(compositemodelroute.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(compositemodelroute.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.ParentGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.ParentGroupTable,
			Columns: []string{compositemodelroute.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.ParentGroupTable,
			Columns: []string{compositemodelroute.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.TargetGroupTable,
			Columns: []string{compositemodelroute.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.TargetGroupTable,
			Columns: []string{compositemodelroute.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{compositemodelroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CompositeModelRouteUpdateOne is the builder for updating a single CompositeModelRoute entity.
type CompositeModelRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CompositeModelRouteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CompositeModelRouteUpdateOne) SetUpdatedAt(v time.Time) *CompositeModelRouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetParentGroupID sets the "parent_group_id" field.
func (_u *CompositeModelRouteUpdateOne) SetParentGroupID(v int64) *CompositeModelRouteUpdateOne {
	_u.mutation.SetParentGroupID(v)
	return _u
}

// SetNillableParentGroupID sets the "parent_group_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillableParentGroupID(v *int64) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetParentGroupID(*v)
	}
	return _u
}

// SetDisplayModelID sets the "display_model_id" field.
func (_u *CompositeModelRouteUpdateOne) SetDisplayModelID(v string) *CompositeModelRouteUpdateOne {
	_u.mutation.SetDisplayModelID(v)
	return _u
}

// SetNillableDisplayModelID sets the "display_model_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillableDisplayModelID(v *string) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetDisplayModelID(*v)
	}
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *CompositeModelRouteUpdateOne) SetTargetGroupID(v int64) *CompositeModelRouteUpdateOne {
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillableTargetGroupID(v *int64) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// SetTargetModelID sets the "target_model_id" field.
func (_u *CompositeModelRouteUpdateOne) SetTargetModelID(v string) *CompositeModelRouteUpdateOne {
	_u.mutation.SetTargetModelID(v)
	return _u
}

// SetNillableTargetModelID sets the "target_model_id" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillableTargetModelID(v *string) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetTargetModelID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *CompositeModelRouteUpdateOne) SetPriority(v int) *CompositeModelRouteUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillablePriority(v *int) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *CompositeModelRouteUpdateOne) AddPriority(v int) *CompositeModelRouteUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CompositeModelRouteUpdateOne) SetEnabled(v bool) *CompositeModelRouteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillableEnabled(v *bool) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *CompositeModelRouteUpdateOne) SetNotes(v string) *CompositeModelRouteUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *CompositeModelRouteUpdateOne) SetNillableNotes(v *string) *CompositeModelRouteUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetParentGroup sets the "parent_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdateOne) SetParentGroup(v *Group) *CompositeModelRouteUpdateOne {
	return _u.SetParentGroupID(v.ID)
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdateOne) SetTargetGroup(v *Group) *CompositeModelRouteUpdateOne {
	return _u.SetTargetGroupID(v.ID)
}

// Mutation returns the CompositeModelRouteMutation object of the builder.
func (_u *CompositeModelRouteUpdateOne) Mutation() *CompositeModelRouteMutation {
	return _u.mutation
}

// ClearParentGroup clears the "parent_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdateOne) ClearParentGroup() *CompositeModelRouteUpdateOne {
	_u.mutation.ClearParentGroup()
	return _u
}

// ClearTargetGroup clears the "target_group" edge to the Group entity.
func (_u *CompositeModelRouteUpdateOne) ClearTargetGroup() *CompositeModelRouteUpdateOne {
	_u.mutation.ClearTargetGroup()
	return _u
}

// Where appends a list predicates to the CompositeModelRouteUpdate builder.
func (_u *CompositeModelRouteUpdateOne) Where(ps ...predicate.CompositeModelRoute) *CompositeModelRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CompositeModelRouteUpdateOne) Select(field string, fields ...string) *CompositeModelRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CompositeModelRoute entity.
func (_u *CompositeModelRouteUpdateOne) Save(ctx context.Context) (*CompositeModelRoute, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CompositeModelRouteUpdateOne) SaveX(ctx context.Context) *CompositeModelRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CompositeModelRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CompositeModelRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CompositeModelRouteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := compositemodelroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CompositeModelRouteUpdateOne) check() error {
	if v, ok := _u.mutation.DisplayModelID(); ok {
		if err := compositemodelroute.DisplayModelIDValidator(v); err != nil {
			return &ValidationError{Name: "display_model_id", err: fmt.Errorf(`ent: validator failed for field "CompositeModelRoute.display_model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetModelID(); ok {
		if err := compositemodelroute.TargetModelIDValidator(v); err != nil {
			return &ValidationError{Name: "target_model_id", err: fmt.Errorf(`ent: validator failed for field "CompositeModelRoute.target_model_id": %w`, err)}
		}
	}
	if _u.mutation.ParentGroupCleared() && len(_u.mutation.ParentGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompositeModelRoute.parent_group"`)
	}
	if _u.mutation.TargetGroupCleared() && len(_u.mutation.TargetGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CompositeModelRoute.target_group"`)
	}
	return nil
}

func (_u *CompositeModelRouteUpdateOne) sqlSave(ctx context.Context) (_node *CompositeModelRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(compositemodelroute.Table, compositemodelroute.Columns, sqlgraph.NewFieldSpec(compositemodelroute.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CompositeModelRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, compositemodelroute.FieldID)
		for _, f := range fields {
			if !compositemodelroute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != compositemodelroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(compositemodelroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DisplayModelID(); ok {
		_spec.SetField(compositemodelroute.FieldDisplayModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetModelID(); ok {
		_spec.SetField(compositemodelroute.FieldTargetModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(compositemodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(compositemodelroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(compositemodelroute.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(compositemodelroute.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.ParentGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.ParentGroupTable,
			Columns: []string{compositemodelroute.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.ParentGroupTable,
			Columns: []string{compositemodelroute.ParentGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.TargetGroupTable,
			Columns: []string{compositemodelroute.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   compositemodelroute.TargetGroupTable,
			Columns: []string{compositemodelroute.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CompositeModelRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{compositemodelroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
