// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// CompositeModelRoute is the model entity for the CompositeModelRoute schema.
type CompositeModelRoute struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ParentGroupID holds the value of the "parent_group_id" field.
	ParentGroupID int64 `json:"parent_group_id,omitempty"`
	// DisplayModelID holds the value of the "display_model_id" field.
	DisplayModelID string `json:"display_model_id,omitempty"`
	// TargetGroupID holds the value of the "target_group_id" field.
	TargetGroupID int64 `json:"target_group_id,omitempty"`
	// TargetModelID holds the value of the "target_model_id" field.
	TargetModelID string `json:"target_model_id,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompositeModelRouteQuery when eager-loading is set.
	Edges        CompositeModelRouteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CompositeModelRouteEdges holds the relations/edges for other nodes in the graph.
type CompositeModelRouteEdges struct {
	// ParentGroup holds the value of the parent_group edge.
	ParentGroup *Group `json:"parent_group,omitempty"`
	// TargetGroup holds the value of the target_group edge.
	TargetGroup *Group `json:"target_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentGroupOrErr returns the ParentGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompositeModelRouteEdges) ParentGroupOrErr() (*Group, error) {
	if e.ParentGroup != nil {
		return e.ParentGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "parent_group"}
}

// TargetGroupOrErr returns the TargetGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompositeModelRouteEdges) TargetGroupOrErr() (*Group, error) {
	if e.TargetGroup != nil {
		return e.TargetGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "target_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CompositeModelRoute) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case compositemodelroute.FieldEnabled:
			values[i] = new(sql.NullBool)
		case compositemodelroute.FieldID, compositemodelroute.FieldParentGroupID, compositemodelroute.FieldTargetGroupID, compositemodelroute.FieldPriority:
			values[i] = new(sql.NullInt64)
		case compositemodelroute.FieldDisplayModelID, compositemodelroute.FieldTargetModelID, compositemodelroute.FieldNotes:
			values[i] = new(sql.NullString)
		case compositemodelroute.FieldCreatedAt, compositemodelroute.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CompositeModelRoute fields.
func (_m *CompositeModelRoute) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case compositemodelroute.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case compositemodelroute.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case compositemodelroute.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case compositemodelroute.FieldParentGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_group_id", values[i])
			} else if value.Valid {
				_m.ParentGroupID = value.Int64
			}
		case compositemodelroute.FieldDisplayModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_model_id", values[i])
			} else if value.Valid {
				_m.DisplayModelID = value.String
			}
		case compositemodelroute.FieldTargetGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_group_id", values[i])
			} else if value.Valid {
				_m.TargetGroupID = value.Int64
			}
		case compositemodelroute.FieldTargetModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_model_id", values[i])
			} else if value.Valid {
				_m.TargetModelID = value.String
			}
		case compositemodelroute.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case compositemodelroute.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case compositemodelroute.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CompositeModelRoute.
// This includes values selected through modifiers, order, etc.
func (_m *CompositeModelRoute) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParentGroup queries the "parent_group" edge of the CompositeModelRoute entity.
func (_m *CompositeModelRoute) QueryParentGroup() *GroupQuery {
	return NewCompositeModelRouteClient(_m.config).QueryParentGroup(_m)
}

// QueryTargetGroup queries the "target_group" edge of the CompositeModelRoute entity.
func (_m *CompositeModelRoute) QueryTargetGroup() *GroupQuery {
	return NewCompositeModelRouteClient(_m.config).QueryTargetGroup(_m)
}

// Update returns a builder for updating this CompositeModelRoute.
// Note that you need to call CompositeModelRoute.Unwrap() before calling this method if this CompositeModelRoute
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CompositeModelRoute) Update() *CompositeModelRouteUpdateOne {
	return NewCompositeModelRouteClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CompositeModelRoute entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CompositeModelRoute) Unwrap() *CompositeModelRoute {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CompositeModelRoute is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CompositeModelRoute) String() string {
	var builder strings.Builder
	builder.WriteString("CompositeModelRoute(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("parent_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentGroupID))
	builder.WriteString(", ")
	builder.WriteString("display_model_id=")
	builder.WriteString(_m.DisplayModelID)
	builder.WriteString(", ")
	builder.WriteString("target_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetGroupID))
	builder.WriteString(", ")
	builder.WriteString("target_model_id=")
	builder.WriteString(_m.TargetModelID)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// CompositeModelRoutes is a parsable slice of CompositeModelRoute.
type CompositeModelRoutes []*CompositeModelRoute
