// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/passkeyuserhandle"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PasskeyUserHandle is the model entity for the PasskeyUserHandle schema.
type PasskeyUserHandle struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// UserHandle holds the value of the "user_handle" field.
	UserHandle []byte `json:"user_handle,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PasskeyUserHandleQuery when eager-loading is set.
	Edges        PasskeyUserHandleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PasskeyUserHandleEdges holds the relations/edges for other nodes in the graph.
type PasskeyUserHandleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PasskeyUserHandleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PasskeyUserHandle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passkeyuserhandle.FieldUserHandle:
			values[i] = new([]byte)
		case passkeyuserhandle.FieldID, passkeyuserhandle.FieldUserID:
			values[i] = new(sql.NullInt64)
		case passkeyuserhandle.FieldCreatedAt, passkeyuserhandle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PasskeyUserHandle fields.
func (_m *PasskeyUserHandle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passkeyuserhandle.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case passkeyuserhandle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case passkeyuserhandle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case passkeyuserhandle.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case passkeyuserhandle.FieldUserHandle:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field user_handle", values[i])
			} else if value != nil {
				_m.UserHandle = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PasskeyUserHandle.
// This includes values selected through modifiers, order, etc.
func (_m *PasskeyUserHandle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PasskeyUserHandle entity.
func (_m *PasskeyUserHandle) QueryUser() *UserQuery {
	return NewPasskeyUserHandleClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PasskeyUserHandle.
// Note that you need to call PasskeyUserHandle.Unwrap() before calling this method if this PasskeyUserHandle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PasskeyUserHandle) Update() *PasskeyUserHandleUpdateOne {
	return NewPasskeyUserHandleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PasskeyUserHandle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PasskeyUserHandle) Unwrap() *PasskeyUserHandle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PasskeyUserHandle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PasskeyUserHandle) String() string {
	var builder strings.Builder
	builder.WriteString("PasskeyUserHandle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("user_handle=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserHandle))
	builder.WriteByte(')')
	return builder.String()
}

// PasskeyUserHandles is a parsable slice of PasskeyUserHandle.
type PasskeyUserHandles []*PasskeyUserHandle
