// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/passkeyuserhandle"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PasskeyUserHandleUpdate is the builder for updating PasskeyUserHandle entities.
type PasskeyUserHandleUpdate struct {
	config
	hooks    []Hook
	mutation *PasskeyUserHandleMutation
}

// Where appends a list predicates to the PasskeyUserHandleUpdate builder.
func (_u *PasskeyUserHandleUpdate) Where(ps ...predicate.PasskeyUserHandle) *PasskeyUserHandleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasskeyUserHandleUpdate) SetUpdatedAt(v time.Time) *PasskeyUserHandleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PasskeyUserHandleUpdate) SetUserID(v int64) *PasskeyUserHandleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PasskeyUserHandleUpdate) SetNillableUserID(v *int64) *PasskeyUserHandleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserHandle sets the "user_handle" field.
func (_u *PasskeyUserHandleUpdate) SetUserHandle(v []byte) *PasskeyUserHandleUpdate {
	_u.mutation.SetUserHandle(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasskeyUserHandleUpdate) SetUser(v *User) *PasskeyUserHandleUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PasskeyUserHandleMutation object of the builder.
func (_u *PasskeyUserHandleUpdate) Mutation() *PasskeyUserHandleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasskeyUserHandleUpdate) ClearUser() *PasskeyUserHandleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasskeyUserHandleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyUserHandleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasskeyUserHandleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyUserHandleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyUserHandleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkeyuserhandle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyUserHandleUpdate) check() error {
	if v, ok := _u.mutation.UserHandle(); ok {
		if err := passkeyuserhandle.UserHandleValidator(v); err != nil {
			return &ValidationError{Name: "user_handle", err: fmt.Errorf(`ent: validator failed for field "PasskeyUserHandle.user_handle": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasskeyUserHandle.user"`)
	}
	return nil
}

func (_u *PasskeyUserHandleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkeyuserhandle.Table, passkeyuserhandle.Columns, sqlgraph.NewFieldSpec(passkeyuserhandle.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkeyuserhandle.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserHandle(); ok {
		_spec.SetField(passkeyuserhandle.FieldUserHandle, field.TypeBytes, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeyuserhandle.UserTable,
			Columns: []string{passkeyuserhandle.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeyuserhandle.UserTable,
			Columns: []string{passkeyuserhandle.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkeyuserhandle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasskeyUserHandleUpdateOne is the builder for updating a single PasskeyUserHandle entity.
type PasskeyUserHandleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasskeyUserHandleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasskeyUserHandleUpdateOne) SetUpdatedAt(v time.Time) *PasskeyUserHandleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PasskeyUserHandleUpdateOne) SetUserID(v int64) *PasskeyUserHandleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PasskeyUserHandleUpdateOne) SetNillableUserID(v *int64) *PasskeyUserHandleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUserHandle sets the "user_handle" field.
func (_u *PasskeyUserHandleUpdateOne) SetUserHandle(v []byte) *PasskeyUserHandleUpdateOne {
	_u.mutation.SetUserHandle(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasskeyUserHandleUpdateOne) SetUser(v *User) *PasskeyUserHandleUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PasskeyUserHandleMutation object of the builder.
func (_u *PasskeyUserHandleUpdateOne) Mutation() *PasskeyUserHandleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasskeyUserHandleUpdateOne) ClearUser() *PasskeyUserHandleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PasskeyUserHandleUpdate builder.
func (_u *PasskeyUserHandleUpdateOne) Where(ps ...predicate.PasskeyUserHandle) *PasskeyUserHandleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasskeyUserHandleUpdateOne) Select(field string, fields ...string) *PasskeyUserHandleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PasskeyUserHandle entity.
func (_u *PasskeyUserHandleUpdateOne) Save(ctx context.Context) (*PasskeyUserHandle, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasskeyUserHandleUpdateOne) SaveX(ctx context.Context) *PasskeyUserHandle {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasskeyUserHandleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasskeyUserHandleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasskeyUserHandleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passkeyuserhandle.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasskeyUserHandleUpdateOne) check() error {
	if v, ok := _u.mutation.UserHandle(); ok {
		if err := passkeyuserhandle.UserHandleValidator(v); err != nil {
			return &ValidationError{Name: "user_handle", err: fmt.Errorf(`ent: validator failed for field "PasskeyUserHandle.user_handle": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasskeyUserHandle.user"`)
	}
	return nil
}

func (_u *PasskeyUserHandleUpdateOne) sqlSave(ctx context.Context) (_node *PasskeyUserHandle, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passkeyuserhandle.Table, passkeyuserhandle.Columns, sqlgraph.NewFieldSpec(passkeyuserhandle.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PasskeyUserHandle.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passkeyuserhandle.FieldID)
		for _, f := range fields {
			if !passkeyuserhandle.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passkeyuserhandle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passkeyuserhandle.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserHandle(); ok {
		_spec.SetField(passkeyuserhandle.FieldUserHandle, field.TypeBytes, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeyuserhandle.UserTable,
			Columns: []string{passkeyuserhandle.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   passkeyuserhandle.UserTable,
			Columns: []string{passkeyuserhandle.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PasskeyUserHandle{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passkeyuserhandle.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
