// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/passkeyuserhandle"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PasskeyUserHandleDelete is the builder for deleting a PasskeyUserHandle entity.
type PasskeyUserHandleDelete struct {
	config
	hooks    []Hook
	mutation *PasskeyUserHandleMutation
}

// Where appends a list predicates to the PasskeyUserHandleDelete builder.
func (_d *PasskeyUserHandleDelete) Where(ps ...predicate.PasskeyUserHandle) *PasskeyUserHandleDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PasskeyUserHandleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PasskeyUserHandleDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PasskeyUserHandleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(passkeyuserhandle.Table, sqlgraph.NewFieldSpec(passkeyuserhandle.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PasskeyUserHandleDeleteOne is the builder for deleting a single PasskeyUserHandle entity.
type PasskeyUserHandleDeleteOne struct {
	_d *PasskeyUserHandleDelete
}

// Where appends a list predicates to the PasskeyUserHandleDelete builder.
func (_d *PasskeyUserHandleDeleteOne) Where(ps ...predicate.PasskeyUserHandle) *PasskeyUserHandleDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PasskeyUserHandleDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{passkeyuserhandle.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PasskeyUserHandleDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
