// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcementread"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/promocodeusage"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userattributevalue"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserCreate) SetCreatedAt(v time.Time) *UserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserCreate) SetUpdatedAt(v time.Time) *UserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdatedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserCreate) SetDeletedAt(v time.Time) *UserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableDeletedAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *UserCreate) SetPasswordHash(v string) *UserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *UserCreate) SetRole(v string) *UserCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *UserCreate) SetNillableRole(v *string) *UserCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetBalance sets the "balance" field.
func (_c *UserCreate) SetBalance(v float64) *UserCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_c *UserCreate) SetNillableBalance(v *float64) *UserCreate {
	if v != nil {
		_c.SetBalance(*v)
	}
	return _c
}

// SetConcurrency sets the "concurrency" field.
func (_c *UserCreate) SetConcurrency(v int) *UserCreate {
	_c.mutation.SetConcurrency(v)
	return _c
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_c *UserCreate) SetNillableConcurrency(v *int) *UserCreate {
	if v != nil {
		_c.SetConcurrency(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserCreate) SetStatus(v string) *UserCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UserCreate) SetNillableStatus(v *string) *UserCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAdminFreeBilling sets the "admin_free_billing" field.
func (_c *UserCreate) SetAdminFreeBilling(v bool) *UserCreate {
	_c.mutation.SetAdminFreeBilling(v)
	return _c
}

// SetNillableAdminFreeBilling sets the "admin_free_billing" field if the given value is not nil.
func (_c *UserCreate) SetNillableAdminFreeBilling(v *bool) *UserCreate {
	if v != nil {
		_c.SetAdminFreeBilling(*v)
	}
	return _c
}

// SetRequestDetailsReview sets the "request_details_review" field.
func (_c *UserCreate) SetRequestDetailsReview(v bool) *UserCreate {
	_c.mutation.SetRequestDetailsReview(v)
	return _c
}

// SetNillableRequestDetailsReview sets the "request_details_review" field if the given value is not nil.
func (_c *UserCreate) SetNillableRequestDetailsReview(v *bool) *UserCreate {
	if v != nil {
		_c.SetRequestDetailsReview(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsername(v *string) *UserCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserCreate) SetNotes(v string) *UserCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserCreate) SetNillableNotes(v *string) *UserCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetUsageModelDisplayMode sets the "usage_model_display_mode" field.
func (_c *UserCreate) SetUsageModelDisplayMode(v string) *UserCreate {
	_c.mutation.SetUsageModelDisplayMode(v)
	return _c
}

// SetNillableUsageModelDisplayMode sets the "usage_model_display_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsageModelDisplayMode(v *string) *UserCreate {
	if v != nil {
		_c.SetUsageModelDisplayMode(*v)
	}
	return _c
}

// SetGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field.
func (_c *UserCreate) SetGlobalRealtimeCountdownEnabled(v bool) *UserCreate {
	_c.mutation.SetGlobalRealtimeCountdownEnabled(v)
	return _c
}

// SetNillableGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableGlobalRealtimeCountdownEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetGlobalRealtimeCountdownEnabled(*v)
	}
	return _c
}

// SetAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field.
func (_c *UserCreate) SetAccountRealtimeCountdownEnabled(v bool) *UserCreate {
	_c.mutation.SetAccountRealtimeCountdownEnabled(v)
	return _c
}

// SetNillableAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableAccountRealtimeCountdownEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetAccountRealtimeCountdownEnabled(*v)
	}
	return _c
}

// SetVisualPresetPreference sets the "visual_preset_preference" field.
func (_c *UserCreate) SetVisualPresetPreference(v string) *UserCreate {
	_c.mutation.SetVisualPresetPreference(v)
	return _c
}

// SetNillableVisualPresetPreference sets the "visual_preset_preference" field if the given value is not nil.
func (_c *UserCreate) SetNillableVisualPresetPreference(v *string) *UserCreate {
	if v != nil {
		_c.SetVisualPresetPreference(*v)
	}
	return _c
}

// SetAccountVisualPresetOverride sets the "account_visual_preset_override" field.
func (_c *UserCreate) SetAccountVisualPresetOverride(v string) *UserCreate {
	_c.mutation.SetAccountVisualPresetOverride(v)
	return _c
}

// SetNillableAccountVisualPresetOverride sets the "account_visual_preset_override" field if the given value is not nil.
func (_c *UserCreate) SetNillableAccountVisualPresetOverride(v *string) *UserCreate {
	if v != nil {
		_c.SetAccountVisualPresetOverride(*v)
	}
	return _c
}

// SetAccountTodayStatsWindows sets the "account_today_stats_windows" field.
func (_c *UserCreate) SetAccountTodayStatsWindows(v []string) *UserCreate {
	_c.mutation.SetAccountTodayStatsWindows(v)
	return _c
}

// SetAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field.
func (_c *UserCreate) SetAccountTodayStatsCycleMode(v string) *UserCreate {
	_c.mutation.SetAccountTodayStatsCycleMode(v)
	return _c
}

// SetNillableAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableAccountTodayStatsCycleMode(v *string) *UserCreate {
	if v != nil {
		_c.SetAccountTodayStatsCycleMode(*v)
	}
	return _c
}

// SetAccountGroupDisplayMode sets the "account_group_display_mode" field.
func (_c *UserCreate) SetAccountGroupDisplayMode(v string) *UserCreate {
	_c.mutation.SetAccountGroupDisplayMode(v)
	return _c
}

// SetNillableAccountGroupDisplayMode sets the "account_group_display_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableAccountGroupDisplayMode(v *string) *UserCreate {
	if v != nil {
		_c.SetAccountGroupDisplayMode(*v)
	}
	return _c
}

// SetAccountStatusDisplayMode sets the "account_status_display_mode" field.
func (_c *UserCreate) SetAccountStatusDisplayMode(v string) *UserCreate {
	_c.mutation.SetAccountStatusDisplayMode(v)
	return _c
}

// SetNillableAccountStatusDisplayMode sets the "account_status_display_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableAccountStatusDisplayMode(v *string) *UserCreate {
	if v != nil {
		_c.SetAccountStatusDisplayMode(*v)
	}
	return _c
}

// SetUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field.
func (_c *UserCreate) SetUsageContextBadgeDisplayMode(v string) *UserCreate {
	_c.mutation.SetUsageContextBadgeDisplayMode(v)
	return _c
}

// SetNillableUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsageContextBadgeDisplayMode(v *string) *UserCreate {
	if v != nil {
		_c.SetUsageContextBadgeDisplayMode(*v)
	}
	return _c
}

// SetAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field.
func (_c *UserCreate) SetAPIKeyModelBindingMode(v string) *UserCreate {
	_c.mutation.SetAPIKeyModelBindingMode(v)
	return _c
}

// SetNillableAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field if the given value is not nil.
func (_c *UserCreate) SetNillableAPIKeyModelBindingMode(v *string) *UserCreate {
	if v != nil {
		_c.SetAPIKeyModelBindingMode(*v)
	}
	return _c
}

// SetAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field.
func (_c *UserCreate) SetAPIKeyAccessTimePolicy(v map[string]interface{}) *UserCreate {
	_c.mutation.SetAPIKeyAccessTimePolicy(v)
	return _c
}

// SetTotpSecretEncrypted sets the "totp_secret_encrypted" field.
func (_c *UserCreate) SetTotpSecretEncrypted(v string) *UserCreate {
	_c.mutation.SetTotpSecretEncrypted(v)
	return _c
}

// SetNillableTotpSecretEncrypted sets the "totp_secret_encrypted" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpSecretEncrypted(v *string) *UserCreate {
	if v != nil {
		_c.SetTotpSecretEncrypted(*v)
	}
	return _c
}

// SetTotpEnabled sets the "totp_enabled" field.
func (_c *UserCreate) SetTotpEnabled(v bool) *UserCreate {
	_c.mutation.SetTotpEnabled(v)
	return _c
}

// SetNillableTotpEnabled sets the "totp_enabled" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpEnabled(v *bool) *UserCreate {
	if v != nil {
		_c.SetTotpEnabled(*v)
	}
	return _c
}

// SetTotpEnabledAt sets the "totp_enabled_at" field.
func (_c *UserCreate) SetTotpEnabledAt(v time.Time) *UserCreate {
	_c.mutation.SetTotpEnabledAt(v)
	return _c
}

// SetNillableTotpEnabledAt sets the "totp_enabled_at" field if the given value is not nil.
func (_c *UserCreate) SetNillableTotpEnabledAt(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetTotpEnabledAt(*v)
	}
	return _c
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *UserCreate) AddAPIKeyIDs(ids ...int64) *UserCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *UserCreate) AddAPIKeys(v ...*APIKey) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// AddRedeemCodeIDs adds the "redeem_codes" edge to the RedeemCode entity by IDs.
func (_c *UserCreate) AddRedeemCodeIDs(ids ...int64) *UserCreate {
	_c.mutation.AddRedeemCodeIDs(ids...)
	return _c
}

// AddRedeemCodes adds the "redeem_codes" edges to the RedeemCode entity.
func (_c *UserCreate) AddRedeemCodes(v ...*RedeemCode) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRedeemCodeIDs(ids...)
}

// AddSubscriptionIDs adds the "subscriptions" edge to the UserSubscription entity by IDs.
func (_c *UserCreate) AddSubscriptionIDs(ids ...int64) *UserCreate {
	_c.mutation.AddSubscriptionIDs(ids...)
	return _c
}

// AddSubscriptions adds the "subscriptions" edges to the UserSubscription entity.
func (_c *UserCreate) AddSubscriptions(v ...*UserSubscription) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSubscriptionIDs(ids...)
}

// AddAssignedSubscriptionIDs adds the "assigned_subscriptions" edge to the UserSubscription entity by IDs.
func (_c *UserCreate) AddAssignedSubscriptionIDs(ids ...int64) *UserCreate {
	_c.mutation.AddAssignedSubscriptionIDs(ids...)
	return _c
}

// AddAssignedSubscriptions adds the "assigned_subscriptions" edges to the UserSubscription entity.
func (_c *UserCreate) AddAssignedSubscriptions(v ...*UserSubscription) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignedSubscriptionIDs(ids...)
}

// AddAnnouncementReadIDs adds the "announcement_reads" edge to the AnnouncementRead entity by IDs.
func (_c *UserCreate) AddAnnouncementReadIDs(ids ...int64) *UserCreate {
	_c.mutation.AddAnnouncementReadIDs(ids...)
	return _c
}

// AddAnnouncementReads adds the "announcement_reads" edges to the AnnouncementRead entity.
func (_c *UserCreate) AddAnnouncementReads(v ...*AnnouncementRead) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAnnouncementReadIDs(ids...)
}

// AddAllowedGroupIDs adds the "allowed_groups" edge to the Group entity by IDs.
func (_c *UserCreate) AddAllowedGroupIDs(ids ...int64) *UserCreate {
	_c.mutation.AddAllowedGroupIDs(ids...)
	return _c
}

// AddAllowedGroups adds the "allowed_groups" edges to the Group entity.
func (_c *UserCreate) AddAllowedGroups(v ...*Group) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAllowedGroupIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *UserCreate) AddUsageLogIDs(ids ...int64) *UserCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *UserCreate) AddUsageLogs(v ...*UsageLog) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// AddAttributeValueIDs adds the "attribute_values" edge to the UserAttributeValue entity by IDs.
func (_c *UserCreate) AddAttributeValueIDs(ids ...int64) *UserCreate {
	_c.mutation.AddAttributeValueIDs(ids...)
	return _c
}

// AddAttributeValues adds the "attribute_values" edges to the UserAttributeValue entity.
func (_c *UserCreate) AddAttributeValues(v ...*UserAttributeValue) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAttributeValueIDs(ids...)
}

// AddPromoCodeUsageIDs adds the "promo_code_usages" edge to the PromoCodeUsage entity by IDs.
func (_c *UserCreate) AddPromoCodeUsageIDs(ids ...int64) *UserCreate {
	_c.mutation.AddPromoCodeUsageIDs(ids...)
	return _c
}

// AddPromoCodeUsages adds the "promo_code_usages" edges to the PromoCodeUsage entity.
func (_c *UserCreate) AddPromoCodeUsages(v ...*PromoCodeUsage) *UserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPromoCodeUsageIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if user.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := user.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if user.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized user.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := user.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := user.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Balance(); !ok {
		v := user.DefaultBalance
		_c.mutation.SetBalance(v)
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		v := user.DefaultConcurrency
		_c.mutation.SetConcurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := user.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AdminFreeBilling(); !ok {
		v := user.DefaultAdminFreeBilling
		_c.mutation.SetAdminFreeBilling(v)
	}
	if _, ok := _c.mutation.RequestDetailsReview(); !ok {
		v := user.DefaultRequestDetailsReview
		_c.mutation.SetRequestDetailsReview(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := user.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := user.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.UsageModelDisplayMode(); !ok {
		v := user.DefaultUsageModelDisplayMode
		_c.mutation.SetUsageModelDisplayMode(v)
	}
	if _, ok := _c.mutation.GlobalRealtimeCountdownEnabled(); !ok {
		v := user.DefaultGlobalRealtimeCountdownEnabled
		_c.mutation.SetGlobalRealtimeCountdownEnabled(v)
	}
	if _, ok := _c.mutation.AccountRealtimeCountdownEnabled(); !ok {
		v := user.DefaultAccountRealtimeCountdownEnabled
		_c.mutation.SetAccountRealtimeCountdownEnabled(v)
	}
	if _, ok := _c.mutation.VisualPresetPreference(); !ok {
		v := user.DefaultVisualPresetPreference
		_c.mutation.SetVisualPresetPreference(v)
	}
	if _, ok := _c.mutation.AccountVisualPresetOverride(); !ok {
		v := user.DefaultAccountVisualPresetOverride
		_c.mutation.SetAccountVisualPresetOverride(v)
	}
	if _, ok := _c.mutation.AccountTodayStatsWindows(); !ok {
		v := user.DefaultAccountTodayStatsWindows
		_c.mutation.SetAccountTodayStatsWindows(v)
	}
	if _, ok := _c.mutation.AccountTodayStatsCycleMode(); !ok {
		v := user.DefaultAccountTodayStatsCycleMode
		_c.mutation.SetAccountTodayStatsCycleMode(v)
	}
	if _, ok := _c.mutation.AccountGroupDisplayMode(); !ok {
		v := user.DefaultAccountGroupDisplayMode
		_c.mutation.SetAccountGroupDisplayMode(v)
	}
	if _, ok := _c.mutation.AccountStatusDisplayMode(); !ok {
		v := user.DefaultAccountStatusDisplayMode
		_c.mutation.SetAccountStatusDisplayMode(v)
	}
	if _, ok := _c.mutation.UsageContextBadgeDisplayMode(); !ok {
		v := user.DefaultUsageContextBadgeDisplayMode
		_c.mutation.SetUsageContextBadgeDisplayMode(v)
	}
	if _, ok := _c.mutation.APIKeyModelBindingMode(); !ok {
		v := user.DefaultAPIKeyModelBindingMode
		_c.mutation.SetAPIKeyModelBindingMode(v)
	}
	if _, ok := _c.mutation.TotpEnabled(); !ok {
		v := user.DefaultTotpEnabled
		_c.mutation.SetTotpEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "User.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "User.balance"`)}
	}
	if _, ok := _c.mutation.Concurrency(); !ok {
		return &ValidationError{Name: "concurrency", err: errors.New(`ent: missing required field "User.concurrency"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "User.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := user.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AdminFreeBilling(); !ok {
		return &ValidationError{Name: "admin_free_billing", err: errors.New(`ent: missing required field "User.admin_free_billing"`)}
	}
	if _, ok := _c.mutation.RequestDetailsReview(); !ok {
		return &ValidationError{Name: "request_details_review", err: errors.New(`ent: missing required field "User.request_details_review"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "User.notes"`)}
	}
	if _, ok := _c.mutation.UsageModelDisplayMode(); !ok {
		return &ValidationError{Name: "usage_model_display_mode", err: errors.New(`ent: missing required field "User.usage_model_display_mode"`)}
	}
	if v, ok := _c.mutation.UsageModelDisplayMode(); ok {
		if err := user.UsageModelDisplayModeValidator(v); err != nil {
			return &ValidationError{Name: "usage_model_display_mode", err: fmt.Errorf(`ent: validator failed for field "User.usage_model_display_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GlobalRealtimeCountdownEnabled(); !ok {
		return &ValidationError{Name: "global_realtime_countdown_enabled", err: errors.New(`ent: missing required field "User.global_realtime_countdown_enabled"`)}
	}
	if _, ok := _c.mutation.AccountRealtimeCountdownEnabled(); !ok {
		return &ValidationError{Name: "account_realtime_countdown_enabled", err: errors.New(`ent: missing required field "User.account_realtime_countdown_enabled"`)}
	}
	if _, ok := _c.mutation.VisualPresetPreference(); !ok {
		return &ValidationError{Name: "visual_preset_preference", err: errors.New(`ent: missing required field "User.visual_preset_preference"`)}
	}
	if v, ok := _c.mutation.VisualPresetPreference(); ok {
		if err := user.VisualPresetPreferenceValidator(v); err != nil {
			return &ValidationError{Name: "visual_preset_preference", err: fmt.Errorf(`ent: validator failed for field "User.visual_preset_preference": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountVisualPresetOverride(); !ok {
		return &ValidationError{Name: "account_visual_preset_override", err: errors.New(`ent: missing required field "User.account_visual_preset_override"`)}
	}
	if v, ok := _c.mutation.AccountVisualPresetOverride(); ok {
		if err := user.AccountVisualPresetOverrideValidator(v); err != nil {
			return &ValidationError{Name: "account_visual_preset_override", err: fmt.Errorf(`ent: validator failed for field "User.account_visual_preset_override": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountTodayStatsWindows(); !ok {
		return &ValidationError{Name: "account_today_stats_windows", err: errors.New(`ent: missing required field "User.account_today_stats_windows"`)}
	}
	if _, ok := _c.mutation.AccountTodayStatsCycleMode(); !ok {
		return &ValidationError{Name: "account_today_stats_cycle_mode", err: errors.New(`ent: missing required field "User.account_today_stats_cycle_mode"`)}
	}
	if v, ok := _c.mutation.AccountTodayStatsCycleMode(); ok {
		if err := user.AccountTodayStatsCycleModeValidator(v); err != nil {
			return &ValidationError{Name: "account_today_stats_cycle_mode", err: fmt.Errorf(`ent: validator failed for field "User.account_today_stats_cycle_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountGroupDisplayMode(); !ok {
		return &ValidationError{Name: "account_group_display_mode", err: errors.New(`ent: missing required field "User.account_group_display_mode"`)}
	}
	if v, ok := _c.mutation.AccountGroupDisplayMode(); ok {
		if err := user.AccountGroupDisplayModeValidator(v); err != nil {
			return &ValidationError{Name: "account_group_display_mode", err: fmt.Errorf(`ent: validator failed for field "User.account_group_display_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountStatusDisplayMode(); !ok {
		return &ValidationError{Name: "account_status_display_mode", err: errors.New(`ent: missing required field "User.account_status_display_mode"`)}
	}
	if v, ok := _c.mutation.AccountStatusDisplayMode(); ok {
		if err := user.AccountStatusDisplayModeValidator(v); err != nil {
			return &ValidationError{Name: "account_status_display_mode", err: fmt.Errorf(`ent: validator failed for field "User.account_status_display_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UsageContextBadgeDisplayMode(); !ok {
		return &ValidationError{Name: "usage_context_badge_display_mode", err: errors.New(`ent: missing required field "User.usage_context_badge_display_mode"`)}
	}
	if v, ok := _c.mutation.UsageContextBadgeDisplayMode(); ok {
		if err := user.UsageContextBadgeDisplayModeValidator(v); err != nil {
			return &ValidationError{Name: "usage_context_badge_display_mode", err: fmt.Errorf(`ent: validator failed for field "User.usage_context_badge_display_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyModelBindingMode(); !ok {
		return &ValidationError{Name: "api_key_model_binding_mode", err: errors.New(`ent: missing required field "User.api_key_model_binding_mode"`)}
	}
	if v, ok := _c.mutation.APIKeyModelBindingMode(); ok {
		if err := user.APIKeyModelBindingModeValidator(v); err != nil {
			return &ValidationError{Name: "api_key_model_binding_mode", err: fmt.Errorf(`ent: validator failed for field "User.api_key_model_binding_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotpEnabled(); !ok {
		return &ValidationError{Name: "totp_enabled", err: errors.New(`ent: missing required field "User.totp_enabled"`)}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(user.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.Concurrency(); ok {
		_spec.SetField(user.FieldConcurrency, field.TypeInt, value)
		_node.Concurrency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AdminFreeBilling(); ok {
		_spec.SetField(user.FieldAdminFreeBilling, field.TypeBool, value)
		_node.AdminFreeBilling = value
	}
	if value, ok := _c.mutation.RequestDetailsReview(); ok {
		_spec.SetField(user.FieldRequestDetailsReview, field.TypeBool, value)
		_node.RequestDetailsReview = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(user.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.UsageModelDisplayMode(); ok {
		_spec.SetField(user.FieldUsageModelDisplayMode, field.TypeString, value)
		_node.UsageModelDisplayMode = value
	}
	if value, ok := _c.mutation.GlobalRealtimeCountdownEnabled(); ok {
		_spec.SetField(user.FieldGlobalRealtimeCountdownEnabled, field.TypeBool, value)
		_node.GlobalRealtimeCountdownEnabled = value
	}
	if value, ok := _c.mutation.AccountRealtimeCountdownEnabled(); ok {
		_spec.SetField(user.FieldAccountRealtimeCountdownEnabled, field.TypeBool, value)
		_node.AccountRealtimeCountdownEnabled = value
	}
	if value, ok := _c.mutation.VisualPresetPreference(); ok {
		_spec.SetField(user.FieldVisualPresetPreference, field.TypeString, value)
		_node.VisualPresetPreference = value
	}
	if value, ok := _c.mutation.AccountVisualPresetOverride(); ok {
		_spec.SetField(user.FieldAccountVisualPresetOverride, field.TypeString, value)
		_node.AccountVisualPresetOverride = value
	}
	if value, ok := _c.mutation.AccountTodayStatsWindows(); ok {
		_spec.SetField(user.FieldAccountTodayStatsWindows, field.TypeJSON, value)
		_node.AccountTodayStatsWindows = value
	}
	if value, ok := _c.mutation.AccountTodayStatsCycleMode(); ok {
		_spec.SetField(user.FieldAccountTodayStatsCycleMode, field.TypeString, value)
		_node.AccountTodayStatsCycleMode = value
	}
	if value, ok := _c.mutation.AccountGroupDisplayMode(); ok {
		_spec.SetField(user.FieldAccountGroupDisplayMode, field.TypeString, value)
		_node.AccountGroupDisplayMode = value
	}
	if value, ok := _c.mutation.AccountStatusDisplayMode(); ok {
		_spec.SetField(user.FieldAccountStatusDisplayMode, field.TypeString, value)
		_node.AccountStatusDisplayMode = value
	}
	if value, ok := _c.mutation.UsageContextBadgeDisplayMode(); ok {
		_spec.SetField(user.FieldUsageContextBadgeDisplayMode, field.TypeString, value)
		_node.UsageContextBadgeDisplayMode = value
	}
	if value, ok := _c.mutation.APIKeyModelBindingMode(); ok {
		_spec.SetField(user.FieldAPIKeyModelBindingMode, field.TypeString, value)
		_node.APIKeyModelBindingMode = value
	}
	if value, ok := _c.mutation.APIKeyAccessTimePolicy(); ok {
		_spec.SetField(user.FieldAPIKeyAccessTimePolicy, field.TypeJSON, value)
		_node.APIKeyAccessTimePolicy = value
	}
	if value, ok := _c.mutation.TotpSecretEncrypted(); ok {
		_spec.SetField(user.FieldTotpSecretEncrypted, field.TypeString, value)
		_node.TotpSecretEncrypted = &value
	}
	if value, ok := _c.mutation.TotpEnabled(); ok {
		_spec.SetField(user.FieldTotpEnabled, field.TypeBool, value)
		_node.TotpEnabled = value
	}
	if value, ok := _c.mutation.TotpEnabledAt(); ok {
		_spec.SetField(user.FieldTotpEnabledAt, field.TypeTime, value)
		_node.TotpEnabledAt = &value
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.APIKeysTable,
			Columns: []string{user.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedeemCodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RedeemCodesTable,
			Columns: []string{user.RedeemCodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubscriptionsTable,
			Columns: []string{user.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignedSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AssignedSubscriptionsTable,
			Columns: []string{user.AssignedSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersubscription.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AnnouncementReadsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AnnouncementReadsTable,
			Columns: []string{user.AnnouncementReadsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(announcementread.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AllowedGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   user.AllowedGroupsTable,
			Columns: user.AllowedGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &UserAllowedGroupCreate{config: _c.config, mutation: newUserAllowedGroupMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.UsageLogsTable,
			Columns: []string{user.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AttributeValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.AttributeValuesTable,
			Columns: []string{user.AttributeValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userattributevalue.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PromoCodeUsagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PromoCodeUsagesTable,
			Columns: []string{user.PromoCodeUsagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(promocodeusage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreate) OnConflict(opts ...sql.ConflictOption) *UserUpsertOne {
	_c.conflict = opts
	return &UserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreate) OnConflictColumns(columns ...string) *UserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertOne{
		create: _c,
	}
}

type (
	// UserUpsertOne is the builder for "upsert"-ing
	//  one User node.
	UserUpsertOne struct {
		create *UserCreate
	}

	// UserUpsert is the "OnConflict" setter.
	UserUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsert) SetUpdatedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateUpdatedAt() *UserUpsert {
	u.SetExcluded(user.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUpsert) SetDeletedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateDeletedAt() *UserUpsert {
	u.SetExcluded(user.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUpsert) ClearDeletedAt() *UserUpsert {
	u.SetNull(user.FieldDeletedAt)
	return u
}

// SetEmail sets the "email" field.
func (u *UserUpsert) SetEmail(v string) *UserUpsert {
	u.Set(user.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserUpsert) UpdateEmail() *UserUpsert {
	u.SetExcluded(user.FieldEmail)
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsert) SetPasswordHash(v string) *UserUpsert {
	u.Set(user.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsert) UpdatePasswordHash() *UserUpsert {
	u.SetExcluded(user.FieldPasswordHash)
	return u
}

// SetRole sets the "role" field.
func (u *UserUpsert) SetRole(v string) *UserUpsert {
	u.Set(user.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *UserUpsert) UpdateRole() *UserUpsert {
	u.SetExcluded(user.FieldRole)
	return u
}

// SetBalance sets the "balance" field.
func (u *UserUpsert) SetBalance(v float64) *UserUpsert {
	u.Set(user.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UserUpsert) UpdateBalance() *UserUpsert {
	u.SetExcluded(user.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *UserUpsert) AddBalance(v float64) *UserUpsert {
	u.Add(user.FieldBalance, v)
	return u
}

// SetConcurrency sets the "concurrency" field.
func (u *UserUpsert) SetConcurrency(v int) *UserUpsert {
	u.Set(user.FieldConcurrency, v)
	return u
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *UserUpsert) UpdateConcurrency() *UserUpsert {
	u.SetExcluded(user.FieldConcurrency)
	return u
}

// AddConcurrency adds v to the "concurrency" field.
func (u *UserUpsert) AddConcurrency(v int) *UserUpsert {
	u.Add(user.FieldConcurrency, v)
	return u
}

// SetStatus sets the "status" field.
func (u *UserUpsert) SetStatus(v string) *UserUpsert {
	u.Set(user.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserUpsert) UpdateStatus() *UserUpsert {
	u.SetExcluded(user.FieldStatus)
	return u
}

// SetAdminFreeBilling sets the "admin_free_billing" field.
func (u *UserUpsert) SetAdminFreeBilling(v bool) *UserUpsert {
	u.Set(user.FieldAdminFreeBilling, v)
	return u
}

// UpdateAdminFreeBilling sets the "admin_free_billing" field to the value that was provided on create.
func (u *UserUpsert) UpdateAdminFreeBilling() *UserUpsert {
	u.SetExcluded(user.FieldAdminFreeBilling)
	return u
}

// SetRequestDetailsReview sets the "request_details_review" field.
func (u *UserUpsert) SetRequestDetailsReview(v bool) *UserUpsert {
	u.Set(user.FieldRequestDetailsReview, v)
	return u
}

// UpdateRequestDetailsReview sets the "request_details_review" field to the value that was provided on create.
func (u *UserUpsert) UpdateRequestDetailsReview() *UserUpsert {
	u.SetExcluded(user.FieldRequestDetailsReview)
	return u
}

// SetUsername sets the "username" field.
func (u *UserUpsert) SetUsername(v string) *UserUpsert {
	u.Set(user.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsert) UpdateUsername() *UserUpsert {
	u.SetExcluded(user.FieldUsername)
	return u
}

// SetNotes sets the "notes" field.
func (u *UserUpsert) SetNotes(v string) *UserUpsert {
	u.Set(user.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserUpsert) UpdateNotes() *UserUpsert {
	u.SetExcluded(user.FieldNotes)
	return u
}

// SetUsageModelDisplayMode sets the "usage_model_display_mode" field.
func (u *UserUpsert) SetUsageModelDisplayMode(v string) *UserUpsert {
	u.Set(user.FieldUsageModelDisplayMode, v)
	return u
}

// UpdateUsageModelDisplayMode sets the "usage_model_display_mode" field to the value that was provided on create.
func (u *UserUpsert) UpdateUsageModelDisplayMode() *UserUpsert {
	u.SetExcluded(user.FieldUsageModelDisplayMode)
	return u
}

// SetGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field.
func (u *UserUpsert) SetGlobalRealtimeCountdownEnabled(v bool) *UserUpsert {
	u.Set(user.FieldGlobalRealtimeCountdownEnabled, v)
	return u
}

// UpdateGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field to the value that was provided on create.
func (u *UserUpsert) UpdateGlobalRealtimeCountdownEnabled() *UserUpsert {
	u.SetExcluded(user.FieldGlobalRealtimeCountdownEnabled)
	return u
}

// SetAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field.
func (u *UserUpsert) SetAccountRealtimeCountdownEnabled(v bool) *UserUpsert {
	u.Set(user.FieldAccountRealtimeCountdownEnabled, v)
	return u
}

// UpdateAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field to the value that was provided on create.
func (u *UserUpsert) UpdateAccountRealtimeCountdownEnabled() *UserUpsert {
	u.SetExcluded(user.FieldAccountRealtimeCountdownEnabled)
	return u
}

// SetVisualPresetPreference sets the "visual_preset_preference" field.
func (u *UserUpsert) SetVisualPresetPreference(v string) *UserUpsert {
	u.Set(user.FieldVisualPresetPreference, v)
	return u
}

// UpdateVisualPresetPreference sets the "visual_preset_preference" field to the value that was provided on create.
func (u *UserUpsert) UpdateVisualPresetPreference() *UserUpsert {
	u.SetExcluded(user.FieldVisualPresetPreference)
	return u
}

// SetAccountVisualPresetOverride sets the "account_visual_preset_override" field.
func (u *UserUpsert) SetAccountVisualPresetOverride(v string) *UserUpsert {
	u.Set(user.FieldAccountVisualPresetOverride, v)
	return u
}

// UpdateAccountVisualPresetOverride sets the "account_visual_preset_override" field to the value that was provided on create.
func (u *UserUpsert) UpdateAccountVisualPresetOverride() *UserUpsert {
	u.SetExcluded(user.FieldAccountVisualPresetOverride)
	return u
}

// SetAccountTodayStatsWindows sets the "account_today_stats_windows" field.
func (u *UserUpsert) SetAccountTodayStatsWindows(v []string) *UserUpsert {
	u.Set(user.FieldAccountTodayStatsWindows, v)
	return u
}

// UpdateAccountTodayStatsWindows sets the "account_today_stats_windows" field to the value that was provided on create.
func (u *UserUpsert) UpdateAccountTodayStatsWindows() *UserUpsert {
	u.SetExcluded(user.FieldAccountTodayStatsWindows)
	return u
}

// SetAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field.
func (u *UserUpsert) SetAccountTodayStatsCycleMode(v string) *UserUpsert {
	u.Set(user.FieldAccountTodayStatsCycleMode, v)
	return u
}

// UpdateAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field to the value that was provided on create.
func (u *UserUpsert) UpdateAccountTodayStatsCycleMode() *UserUpsert {
	u.SetExcluded(user.FieldAccountTodayStatsCycleMode)
	return u
}

// SetAccountGroupDisplayMode sets the "account_group_display_mode" field.
func (u *UserUpsert) SetAccountGroupDisplayMode(v string) *UserUpsert {
	u.Set(user.FieldAccountGroupDisplayMode, v)
	return u
}

// UpdateAccountGroupDisplayMode sets the "account_group_display_mode" field to the value that was provided on create.
func (u *UserUpsert) UpdateAccountGroupDisplayMode() *UserUpsert {
	u.SetExcluded(user.FieldAccountGroupDisplayMode)
	return u
}

// SetAccountStatusDisplayMode sets the "account_status_display_mode" field.
func (u *UserUpsert) SetAccountStatusDisplayMode(v string) *UserUpsert {
	u.Set(user.FieldAccountStatusDisplayMode, v)
	return u
}

// UpdateAccountStatusDisplayMode sets the "account_status_display_mode" field to the value that was provided on create.
func (u *UserUpsert) UpdateAccountStatusDisplayMode() *UserUpsert {
	u.SetExcluded(user.FieldAccountStatusDisplayMode)
	return u
}

// SetUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field.
func (u *UserUpsert) SetUsageContextBadgeDisplayMode(v string) *UserUpsert {
	u.Set(user.FieldUsageContextBadgeDisplayMode, v)
	return u
}

// UpdateUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field to the value that was provided on create.
func (u *UserUpsert) UpdateUsageContextBadgeDisplayMode() *UserUpsert {
	u.SetExcluded(user.FieldUsageContextBadgeDisplayMode)
	return u
}

// SetAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field.
func (u *UserUpsert) SetAPIKeyModelBindingMode(v string) *UserUpsert {
	u.Set(user.FieldAPIKeyModelBindingMode, v)
	return u
}

// UpdateAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field to the value that was provided on create.
func (u *UserUpsert) UpdateAPIKeyModelBindingMode() *UserUpsert {
	u.SetExcluded(user.FieldAPIKeyModelBindingMode)
	return u
}

// SetAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field.
func (u *UserUpsert) SetAPIKeyAccessTimePolicy(v map[string]interface{}) *UserUpsert {
	u.Set(user.FieldAPIKeyAccessTimePolicy, v)
	return u
}

// UpdateAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field to the value that was provided on create.
func (u *UserUpsert) UpdateAPIKeyAccessTimePolicy() *UserUpsert {
	u.SetExcluded(user.FieldAPIKeyAccessTimePolicy)
	return u
}

// ClearAPIKeyAccessTimePolicy clears the value of the "api_key_access_time_policy" field.
func (u *UserUpsert) ClearAPIKeyAccessTimePolicy() *UserUpsert {
	u.SetNull(user.FieldAPIKeyAccessTimePolicy)
	return u
}

// SetTotpSecretEncrypted sets the "totp_secret_encrypted" field.
func (u *UserUpsert) SetTotpSecretEncrypted(v string) *UserUpsert {
	u.Set(user.FieldTotpSecretEncrypted, v)
	return u
}

// UpdateTotpSecretEncrypted sets the "totp_secret_encrypted" field to the value that was provided on create.
func (u *UserUpsert) UpdateTotpSecretEncrypted() *UserUpsert {
	u.SetExcluded(user.FieldTotpSecretEncrypted)
	return u
}

// ClearTotpSecretEncrypted clears the value of the "totp_secret_encrypted" field.
func (u *UserUpsert) ClearTotpSecretEncrypted() *UserUpsert {
	u.SetNull(user.FieldTotpSecretEncrypted)
	return u
}

// SetTotpEnabled sets the "totp_enabled" field.
func (u *UserUpsert) SetTotpEnabled(v bool) *UserUpsert {
	u.Set(user.FieldTotpEnabled, v)
	return u
}

// UpdateTotpEnabled sets the "totp_enabled" field to the value that was provided on create.
func (u *UserUpsert) UpdateTotpEnabled() *UserUpsert {
	u.SetExcluded(user.FieldTotpEnabled)
	return u
}

// SetTotpEnabledAt sets the "totp_enabled_at" field.
func (u *UserUpsert) SetTotpEnabledAt(v time.Time) *UserUpsert {
	u.Set(user.FieldTotpEnabledAt, v)
	return u
}

// UpdateTotpEnabledAt sets the "totp_enabled_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateTotpEnabledAt() *UserUpsert {
	u.SetExcluded(user.FieldTotpEnabledAt)
	return u
}

// ClearTotpEnabledAt clears the value of the "totp_enabled_at" field.
func (u *UserUpsert) ClearTotpEnabledAt() *UserUpsert {
	u.SetNull(user.FieldTotpEnabledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUpsertOne) UpdateNewValues() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(user.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUpsertOne) Ignore() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertOne) DoNothing() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreate.OnConflict
// documentation for more info.
func (u *UserUpsertOne) Update(set func(*UserUpsert)) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsertOne) SetUpdatedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUpdatedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUpsertOne) SetDeletedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateDeletedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUpsertOne) ClearDeletedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEmail sets the "email" field.
func (u *UserUpsertOne) SetEmail(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateEmail() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateEmail()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsertOne) SetPasswordHash(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePasswordHash() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetRole sets the "role" field.
func (u *UserUpsertOne) SetRole(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateRole() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateRole()
	})
}

// SetBalance sets the "balance" field.
func (u *UserUpsertOne) SetBalance(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *UserUpsertOne) AddBalance(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateBalance() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBalance()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *UserUpsertOne) SetConcurrency(v int) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *UserUpsertOne) AddConcurrency(v int) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateConcurrency() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateConcurrency()
	})
}

// SetStatus sets the "status" field.
func (u *UserUpsertOne) SetStatus(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateStatus() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateStatus()
	})
}

// SetAdminFreeBilling sets the "admin_free_billing" field.
func (u *UserUpsertOne) SetAdminFreeBilling(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAdminFreeBilling(v)
	})
}

// UpdateAdminFreeBilling sets the "admin_free_billing" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAdminFreeBilling() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAdminFreeBilling()
	})
}

// SetRequestDetailsReview sets the "request_details_review" field.
func (u *UserUpsertOne) SetRequestDetailsReview(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetRequestDetailsReview(v)
	})
}

// UpdateRequestDetailsReview sets the "request_details_review" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateRequestDetailsReview() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateRequestDetailsReview()
	})
}

// SetUsername sets the "username" field.
func (u *UserUpsertOne) SetUsername(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUsername() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsername()
	})
}

// SetNotes sets the "notes" field.
func (u *UserUpsertOne) SetNotes(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateNotes() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNotes()
	})
}

// SetUsageModelDisplayMode sets the "usage_model_display_mode" field.
func (u *UserUpsertOne) SetUsageModelDisplayMode(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUsageModelDisplayMode(v)
	})
}

// UpdateUsageModelDisplayMode sets the "usage_model_display_mode" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUsageModelDisplayMode() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsageModelDisplayMode()
	})
}

// SetGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field.
func (u *UserUpsertOne) SetGlobalRealtimeCountdownEnabled(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetGlobalRealtimeCountdownEnabled(v)
	})
}

// UpdateGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateGlobalRealtimeCountdownEnabled() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateGlobalRealtimeCountdownEnabled()
	})
}

// SetAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field.
func (u *UserUpsertOne) SetAccountRealtimeCountdownEnabled(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountRealtimeCountdownEnabled(v)
	})
}

// UpdateAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAccountRealtimeCountdownEnabled() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountRealtimeCountdownEnabled()
	})
}

// SetVisualPresetPreference sets the "visual_preset_preference" field.
func (u *UserUpsertOne) SetVisualPresetPreference(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetVisualPresetPreference(v)
	})
}

// UpdateVisualPresetPreference sets the "visual_preset_preference" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateVisualPresetPreference() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateVisualPresetPreference()
	})
}

// SetAccountVisualPresetOverride sets the "account_visual_preset_override" field.
func (u *UserUpsertOne) SetAccountVisualPresetOverride(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountVisualPresetOverride(v)
	})
}

// UpdateAccountVisualPresetOverride sets the "account_visual_preset_override" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAccountVisualPresetOverride() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountVisualPresetOverride()
	})
}

// SetAccountTodayStatsWindows sets the "account_today_stats_windows" field.
func (u *UserUpsertOne) SetAccountTodayStatsWindows(v []string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountTodayStatsWindows(v)
	})
}

// UpdateAccountTodayStatsWindows sets the "account_today_stats_windows" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAccountTodayStatsWindows() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountTodayStatsWindows()
	})
}

// SetAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field.
func (u *UserUpsertOne) SetAccountTodayStatsCycleMode(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountTodayStatsCycleMode(v)
	})
}

// UpdateAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAccountTodayStatsCycleMode() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountTodayStatsCycleMode()
	})
}

// SetAccountGroupDisplayMode sets the "account_group_display_mode" field.
func (u *UserUpsertOne) SetAccountGroupDisplayMode(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountGroupDisplayMode(v)
	})
}

// UpdateAccountGroupDisplayMode sets the "account_group_display_mode" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAccountGroupDisplayMode() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountGroupDisplayMode()
	})
}

// SetAccountStatusDisplayMode sets the "account_status_display_mode" field.
func (u *UserUpsertOne) SetAccountStatusDisplayMode(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountStatusDisplayMode(v)
	})
}

// UpdateAccountStatusDisplayMode sets the "account_status_display_mode" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAccountStatusDisplayMode() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountStatusDisplayMode()
	})
}

// SetUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field.
func (u *UserUpsertOne) SetUsageContextBadgeDisplayMode(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUsageContextBadgeDisplayMode(v)
	})
}

// UpdateUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUsageContextBadgeDisplayMode() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsageContextBadgeDisplayMode()
	})
}

// SetAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field.
func (u *UserUpsertOne) SetAPIKeyModelBindingMode(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAPIKeyModelBindingMode(v)
	})
}

// UpdateAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAPIKeyModelBindingMode() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAPIKeyModelBindingMode()
	})
}

// SetAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field.
func (u *UserUpsertOne) SetAPIKeyAccessTimePolicy(v map[string]interface{}) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAPIKeyAccessTimePolicy(v)
	})
}

// UpdateAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAPIKeyAccessTimePolicy() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAPIKeyAccessTimePolicy()
	})
}

// ClearAPIKeyAccessTimePolicy clears the value of the "api_key_access_time_policy" field.
func (u *UserUpsertOne) ClearAPIKeyAccessTimePolicy() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearAPIKeyAccessTimePolicy()
	})
}

// SetTotpSecretEncrypted sets the "totp_secret_encrypted" field.
func (u *UserUpsertOne) SetTotpSecretEncrypted(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetTotpSecretEncrypted(v)
	})
}

// UpdateTotpSecretEncrypted sets the "totp_secret_encrypted" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateTotpSecretEncrypted() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateTotpSecretEncrypted()
	})
}

// ClearTotpSecretEncrypted clears the value of the "totp_secret_encrypted" field.
func (u *UserUpsertOne) ClearTotpSecretEncrypted() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearTotpSecretEncrypted()
	})
}

// SetTotpEnabled sets the "totp_enabled" field.
func (u *UserUpsertOne) SetTotpEnabled(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetTotpEnabled(v)
	})
}

// UpdateTotpEnabled sets the "totp_enabled" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateTotpEnabled() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateTotpEnabled()
	})
}

// SetTotpEnabledAt sets the "totp_enabled_at" field.
func (u *UserUpsertOne) SetTotpEnabledAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetTotpEnabledAt(v)
	})
}

// UpdateTotpEnabledAt sets the "totp_enabled_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateTotpEnabledAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateTotpEnabledAt()
	})
}

// ClearTotpEnabledAt clears the value of the "totp_enabled_at" field.
func (u *UserUpsertOne) ClearTotpEnabledAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearTotpEnabledAt()
	})
}

// Exec executes the query.
func (u *UserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
	conflict []sql.ConflictOption
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUpsertBulk {
	_c.conflict = opts
	return &UserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreateBulk) OnConflictColumns(columns ...string) *UserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertBulk{
		create: _c,
	}
}

// UserUpsertBulk is the builder for "upsert"-ing
// a bulk of User nodes.
type UserUpsertBulk struct {
	create *UserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserUpsertBulk) UpdateNewValues() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(user.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUpsertBulk) Ignore() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertBulk) DoNothing() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreateBulk.OnConflict
// documentation for more info.
func (u *UserUpsertBulk) Update(set func(*UserUpsert)) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsertBulk) SetUpdatedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUpdatedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUpsertBulk) SetDeletedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateDeletedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUpsertBulk) ClearDeletedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearDeletedAt()
	})
}

// SetEmail sets the "email" field.
func (u *UserUpsertBulk) SetEmail(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateEmail() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateEmail()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *UserUpsertBulk) SetPasswordHash(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePasswordHash() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetRole sets the "role" field.
func (u *UserUpsertBulk) SetRole(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateRole() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateRole()
	})
}

// SetBalance sets the "balance" field.
func (u *UserUpsertBulk) SetBalance(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *UserUpsertBulk) AddBalance(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateBalance() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBalance()
	})
}

// SetConcurrency sets the "concurrency" field.
func (u *UserUpsertBulk) SetConcurrency(v int) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetConcurrency(v)
	})
}

// AddConcurrency adds v to the "concurrency" field.
func (u *UserUpsertBulk) AddConcurrency(v int) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddConcurrency(v)
	})
}

// UpdateConcurrency sets the "concurrency" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateConcurrency() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateConcurrency()
	})
}

// SetStatus sets the "status" field.
func (u *UserUpsertBulk) SetStatus(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateStatus() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateStatus()
	})
}

// SetAdminFreeBilling sets the "admin_free_billing" field.
func (u *UserUpsertBulk) SetAdminFreeBilling(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAdminFreeBilling(v)
	})
}

// UpdateAdminFreeBilling sets the "admin_free_billing" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAdminFreeBilling() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAdminFreeBilling()
	})
}

// SetRequestDetailsReview sets the "request_details_review" field.
func (u *UserUpsertBulk) SetRequestDetailsReview(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetRequestDetailsReview(v)
	})
}

// UpdateRequestDetailsReview sets the "request_details_review" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateRequestDetailsReview() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateRequestDetailsReview()
	})
}

// SetUsername sets the "username" field.
func (u *UserUpsertBulk) SetUsername(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUsername() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsername()
	})
}

// SetNotes sets the "notes" field.
func (u *UserUpsertBulk) SetNotes(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateNotes() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNotes()
	})
}

// SetUsageModelDisplayMode sets the "usage_model_display_mode" field.
func (u *UserUpsertBulk) SetUsageModelDisplayMode(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUsageModelDisplayMode(v)
	})
}

// UpdateUsageModelDisplayMode sets the "usage_model_display_mode" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUsageModelDisplayMode() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsageModelDisplayMode()
	})
}

// SetGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field.
func (u *UserUpsertBulk) SetGlobalRealtimeCountdownEnabled(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetGlobalRealtimeCountdownEnabled(v)
	})
}

// UpdateGlobalRealtimeCountdownEnabled sets the "global_realtime_countdown_enabled" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateGlobalRealtimeCountdownEnabled() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateGlobalRealtimeCountdownEnabled()
	})
}

// SetAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field.
func (u *UserUpsertBulk) SetAccountRealtimeCountdownEnabled(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountRealtimeCountdownEnabled(v)
	})
}

// UpdateAccountRealtimeCountdownEnabled sets the "account_realtime_countdown_enabled" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAccountRealtimeCountdownEnabled() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountRealtimeCountdownEnabled()
	})
}

// SetVisualPresetPreference sets the "visual_preset_preference" field.
func (u *UserUpsertBulk) SetVisualPresetPreference(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetVisualPresetPreference(v)
	})
}

// UpdateVisualPresetPreference sets the "visual_preset_preference" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateVisualPresetPreference() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateVisualPresetPreference()
	})
}

// SetAccountVisualPresetOverride sets the "account_visual_preset_override" field.
func (u *UserUpsertBulk) SetAccountVisualPresetOverride(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountVisualPresetOverride(v)
	})
}

// UpdateAccountVisualPresetOverride sets the "account_visual_preset_override" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAccountVisualPresetOverride() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountVisualPresetOverride()
	})
}

// SetAccountTodayStatsWindows sets the "account_today_stats_windows" field.
func (u *UserUpsertBulk) SetAccountTodayStatsWindows(v []string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountTodayStatsWindows(v)
	})
}

// UpdateAccountTodayStatsWindows sets the "account_today_stats_windows" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAccountTodayStatsWindows() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountTodayStatsWindows()
	})
}

// SetAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field.
func (u *UserUpsertBulk) SetAccountTodayStatsCycleMode(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountTodayStatsCycleMode(v)
	})
}

// UpdateAccountTodayStatsCycleMode sets the "account_today_stats_cycle_mode" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAccountTodayStatsCycleMode() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountTodayStatsCycleMode()
	})
}

// SetAccountGroupDisplayMode sets the "account_group_display_mode" field.
func (u *UserUpsertBulk) SetAccountGroupDisplayMode(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountGroupDisplayMode(v)
	})
}

// UpdateAccountGroupDisplayMode sets the "account_group_display_mode" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAccountGroupDisplayMode() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountGroupDisplayMode()
	})
}

// SetAccountStatusDisplayMode sets the "account_status_display_mode" field.
func (u *UserUpsertBulk) SetAccountStatusDisplayMode(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAccountStatusDisplayMode(v)
	})
}

// UpdateAccountStatusDisplayMode sets the "account_status_display_mode" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAccountStatusDisplayMode() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAccountStatusDisplayMode()
	})
}

// SetUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field.
func (u *UserUpsertBulk) SetUsageContextBadgeDisplayMode(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUsageContextBadgeDisplayMode(v)
	})
}

// UpdateUsageContextBadgeDisplayMode sets the "usage_context_badge_display_mode" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUsageContextBadgeDisplayMode() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsageContextBadgeDisplayMode()
	})
}

// SetAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field.
func (u *UserUpsertBulk) SetAPIKeyModelBindingMode(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAPIKeyModelBindingMode(v)
	})
}

// UpdateAPIKeyModelBindingMode sets the "api_key_model_binding_mode" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAPIKeyModelBindingMode() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAPIKeyModelBindingMode()
	})
}

// SetAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field.
func (u *UserUpsertBulk) SetAPIKeyAccessTimePolicy(v map[string]interface{}) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAPIKeyAccessTimePolicy(v)
	})
}

// UpdateAPIKeyAccessTimePolicy sets the "api_key_access_time_policy" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAPIKeyAccessTimePolicy() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAPIKeyAccessTimePolicy()
	})
}

// ClearAPIKeyAccessTimePolicy clears the value of the "api_key_access_time_policy" field.
func (u *UserUpsertBulk) ClearAPIKeyAccessTimePolicy() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearAPIKeyAccessTimePolicy()
	})
}

// SetTotpSecretEncrypted sets the "totp_secret_encrypted" field.
func (u *UserUpsertBulk) SetTotpSecretEncrypted(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetTotpSecretEncrypted(v)
	})
}

// UpdateTotpSecretEncrypted sets the "totp_secret_encrypted" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateTotpSecretEncrypted() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateTotpSecretEncrypted()
	})
}

// ClearTotpSecretEncrypted clears the value of the "totp_secret_encrypted" field.
func (u *UserUpsertBulk) ClearTotpSecretEncrypted() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearTotpSecretEncrypted()
	})
}

// SetTotpEnabled sets the "totp_enabled" field.
func (u *UserUpsertBulk) SetTotpEnabled(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetTotpEnabled(v)
	})
}

// UpdateTotpEnabled sets the "totp_enabled" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateTotpEnabled() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateTotpEnabled()
	})
}

// SetTotpEnabledAt sets the "totp_enabled_at" field.
func (u *UserUpsertBulk) SetTotpEnabledAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetTotpEnabledAt(v)
	})
}

// UpdateTotpEnabledAt sets the "totp_enabled_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateTotpEnabledAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateTotpEnabledAt()
	})
}

// ClearTotpEnabledAt clears the value of the "totp_enabled_at" field.
func (u *UserUpsertBulk) ClearTotpEnabledAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearTotpEnabledAt()
	})
}

// Exec executes the query.
func (u *UserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
