// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance float64 `json:"balance,omitempty"`
	// Concurrency holds the value of the "concurrency" field.
	Concurrency int `json:"concurrency,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AdminFreeBilling holds the value of the "admin_free_billing" field.
	AdminFreeBilling bool `json:"admin_free_billing,omitempty"`
	// RequestDetailsReview holds the value of the "request_details_review" field.
	RequestDetailsReview bool `json:"request_details_review,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// UsageModelDisplayMode holds the value of the "usage_model_display_mode" field.
	UsageModelDisplayMode string `json:"usage_model_display_mode,omitempty"`
	// GlobalRealtimeCountdownEnabled holds the value of the "global_realtime_countdown_enabled" field.
	GlobalRealtimeCountdownEnabled bool `json:"global_realtime_countdown_enabled,omitempty"`
	// AccountRealtimeCountdownEnabled holds the value of the "account_realtime_countdown_enabled" field.
	AccountRealtimeCountdownEnabled bool `json:"account_realtime_countdown_enabled,omitempty"`
	// VisualPresetPreference holds the value of the "visual_preset_preference" field.
	VisualPresetPreference string `json:"visual_preset_preference,omitempty"`
	// AccountVisualPresetOverride holds the value of the "account_visual_preset_override" field.
	AccountVisualPresetOverride string `json:"account_visual_preset_override,omitempty"`
	// AccountTodayStatsWindows holds the value of the "account_today_stats_windows" field.
	AccountTodayStatsWindows []string `json:"account_today_stats_windows,omitempty"`
	// AccountTodayStatsCycleMode holds the value of the "account_today_stats_cycle_mode" field.
	AccountTodayStatsCycleMode string `json:"account_today_stats_cycle_mode,omitempty"`
	// AccountGroupDisplayMode holds the value of the "account_group_display_mode" field.
	AccountGroupDisplayMode string `json:"account_group_display_mode,omitempty"`
	// AccountStatusDisplayMode holds the value of the "account_status_display_mode" field.
	AccountStatusDisplayMode string `json:"account_status_display_mode,omitempty"`
	// UsageContextBadgeDisplayMode holds the value of the "usage_context_badge_display_mode" field.
	UsageContextBadgeDisplayMode string `json:"usage_context_badge_display_mode,omitempty"`
	// APIKeyModelBindingMode holds the value of the "api_key_model_binding_mode" field.
	APIKeyModelBindingMode string `json:"api_key_model_binding_mode,omitempty"`
	// ExternalModelCatalogViewMode holds the value of the "external_model_catalog_view_mode" field.
	ExternalModelCatalogViewMode string `json:"external_model_catalog_view_mode,omitempty"`
	// Hard upper time access policy for API keys owned by this user
	APIKeyAccessTimePolicy map[string]interface{} `json:"api_key_access_time_policy,omitempty"`
	// TotpSecretEncrypted holds the value of the "totp_secret_encrypted" field.
	TotpSecretEncrypted *string `json:"totp_secret_encrypted,omitempty"`
	// TotpEnabled holds the value of the "totp_enabled" field.
	TotpEnabled bool `json:"totp_enabled,omitempty"`
	// TotpEnabledAt holds the value of the "totp_enabled_at" field.
	TotpEnabledAt *time.Time `json:"totp_enabled_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// RedeemCodes holds the value of the redeem_codes edge.
	RedeemCodes []*RedeemCode `json:"redeem_codes,omitempty"`
	// Subscriptions holds the value of the subscriptions edge.
	Subscriptions []*UserSubscription `json:"subscriptions,omitempty"`
	// AssignedSubscriptions holds the value of the assigned_subscriptions edge.
	AssignedSubscriptions []*UserSubscription `json:"assigned_subscriptions,omitempty"`
	// AnnouncementReads holds the value of the announcement_reads edge.
	AnnouncementReads []*AnnouncementRead `json:"announcement_reads,omitempty"`
	// AllowedGroups holds the value of the allowed_groups edge.
	AllowedGroups []*Group `json:"allowed_groups,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// AttributeValues holds the value of the attribute_values edge.
	AttributeValues []*UserAttributeValue `json:"attribute_values,omitempty"`
	// PromoCodeUsages holds the value of the promo_code_usages edge.
	PromoCodeUsages []*PromoCodeUsage `json:"promo_code_usages,omitempty"`
	// UserAllowedGroups holds the value of the user_allowed_groups edge.
	UserAllowedGroups []*UserAllowedGroup `json:"user_allowed_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [10]bool
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[0] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// RedeemCodesOrErr returns the RedeemCodes value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RedeemCodesOrErr() ([]*RedeemCode, error) {
	if e.loadedTypes[1] {
		return e.RedeemCodes, nil
	}
	return nil, &NotLoadedError{edge: "redeem_codes"}
}

// SubscriptionsOrErr returns the Subscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[2] {
		return e.Subscriptions, nil
	}
	return nil, &NotLoadedError{edge: "subscriptions"}
}

// AssignedSubscriptionsOrErr returns the AssignedSubscriptions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AssignedSubscriptionsOrErr() ([]*UserSubscription, error) {
	if e.loadedTypes[3] {
		return e.AssignedSubscriptions, nil
	}
	return nil, &NotLoadedError{edge: "assigned_subscriptions"}
}

// AnnouncementReadsOrErr returns the AnnouncementReads value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AnnouncementReadsOrErr() ([]*AnnouncementRead, error) {
	if e.loadedTypes[4] {
		return e.AnnouncementReads, nil
	}
	return nil, &NotLoadedError{edge: "announcement_reads"}
}

// AllowedGroupsOrErr returns the AllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AllowedGroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[5] {
		return e.AllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "allowed_groups"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[6] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// AttributeValuesOrErr returns the AttributeValues value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AttributeValuesOrErr() ([]*UserAttributeValue, error) {
	if e.loadedTypes[7] {
		return e.AttributeValues, nil
	}
	return nil, &NotLoadedError{edge: "attribute_values"}
}

// PromoCodeUsagesOrErr returns the PromoCodeUsages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PromoCodeUsagesOrErr() ([]*PromoCodeUsage, error) {
	if e.loadedTypes[8] {
		return e.PromoCodeUsages, nil
	}
	return nil, &NotLoadedError{edge: "promo_code_usages"}
}

// UserAllowedGroupsOrErr returns the UserAllowedGroups value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) UserAllowedGroupsOrErr() ([]*UserAllowedGroup, error) {
	if e.loadedTypes[9] {
		return e.UserAllowedGroups, nil
	}
	return nil, &NotLoadedError{edge: "user_allowed_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldAccountTodayStatsWindows, user.FieldAPIKeyAccessTimePolicy:
			values[i] = new([]byte)
		case user.FieldAdminFreeBilling, user.FieldRequestDetailsReview, user.FieldGlobalRealtimeCountdownEnabled, user.FieldAccountRealtimeCountdownEnabled, user.FieldTotpEnabled:
			values[i] = new(sql.NullBool)
		case user.FieldBalance:
			values[i] = new(sql.NullFloat64)
		case user.FieldID, user.FieldConcurrency:
			values[i] = new(sql.NullInt64)
		case user.FieldEmail, user.FieldPasswordHash, user.FieldRole, user.FieldStatus, user.FieldUsername, user.FieldNotes, user.FieldUsageModelDisplayMode, user.FieldVisualPresetPreference, user.FieldAccountVisualPresetOverride, user.FieldAccountTodayStatsCycleMode, user.FieldAccountGroupDisplayMode, user.FieldAccountStatusDisplayMode, user.FieldUsageContextBadgeDisplayMode, user.FieldAPIKeyModelBindingMode, user.FieldExternalModelCatalogViewMode, user.FieldTotpSecretEncrypted:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt, user.FieldDeletedAt, user.FieldTotpEnabledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case user.FieldBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Float64
			}
		case user.FieldConcurrency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field concurrency", values[i])
			} else if value.Valid {
				_m.Concurrency = int(value.Int64)
			}
		case user.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case user.FieldAdminFreeBilling:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field admin_free_billing", values[i])
			} else if value.Valid {
				_m.AdminFreeBilling = value.Bool
			}
		case user.FieldRequestDetailsReview:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_details_review", values[i])
			} else if value.Valid {
				_m.RequestDetailsReview = value.Bool
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case user.FieldUsageModelDisplayMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_model_display_mode", values[i])
			} else if value.Valid {
				_m.UsageModelDisplayMode = value.String
			}
		case user.FieldGlobalRealtimeCountdownEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field global_realtime_countdown_enabled", values[i])
			} else if value.Valid {
				_m.GlobalRealtimeCountdownEnabled = value.Bool
			}
		case user.FieldAccountRealtimeCountdownEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field account_realtime_countdown_enabled", values[i])
			} else if value.Valid {
				_m.AccountRealtimeCountdownEnabled = value.Bool
			}
		case user.FieldVisualPresetPreference:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visual_preset_preference", values[i])
			} else if value.Valid {
				_m.VisualPresetPreference = value.String
			}
		case user.FieldAccountVisualPresetOverride:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_visual_preset_override", values[i])
			} else if value.Valid {
				_m.AccountVisualPresetOverride = value.String
			}
		case user.FieldAccountTodayStatsWindows:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field account_today_stats_windows", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AccountTodayStatsWindows); err != nil {
					return fmt.Errorf("unmarshal field account_today_stats_windows: %w", err)
				}
			}
		case user.FieldAccountTodayStatsCycleMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_today_stats_cycle_mode", values[i])
			} else if value.Valid {
				_m.AccountTodayStatsCycleMode = value.String
			}
		case user.FieldAccountGroupDisplayMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_group_display_mode", values[i])
			} else if value.Valid {
				_m.AccountGroupDisplayMode = value.String
			}
		case user.FieldAccountStatusDisplayMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_status_display_mode", values[i])
			} else if value.Valid {
				_m.AccountStatusDisplayMode = value.String
			}
		case user.FieldUsageContextBadgeDisplayMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_context_badge_display_mode", values[i])
			} else if value.Valid {
				_m.UsageContextBadgeDisplayMode = value.String
			}
		case user.FieldAPIKeyModelBindingMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_model_binding_mode", values[i])
			} else if value.Valid {
				_m.APIKeyModelBindingMode = value.String
			}
		case user.FieldExternalModelCatalogViewMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_model_catalog_view_mode", values[i])
			} else if value.Valid {
				_m.ExternalModelCatalogViewMode = value.String
			}
		case user.FieldAPIKeyAccessTimePolicy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_access_time_policy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.APIKeyAccessTimePolicy); err != nil {
					return fmt.Errorf("unmarshal field api_key_access_time_policy: %w", err)
				}
			}
		case user.FieldTotpSecretEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field totp_secret_encrypted", values[i])
			} else if value.Valid {
				_m.TotpSecretEncrypted = new(string)
				*_m.TotpSecretEncrypted = value.String
			}
		case user.FieldTotpEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field totp_enabled", values[i])
			} else if value.Valid {
				_m.TotpEnabled = value.Bool
			}
		case user.FieldTotpEnabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field totp_enabled_at", values[i])
			} else if value.Valid {
				_m.TotpEnabledAt = new(time.Time)
				*_m.TotpEnabledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKeys queries the "api_keys" edge of the User entity.
func (_m *User) QueryAPIKeys() *APIKeyQuery {
	return NewUserClient(_m.config).QueryAPIKeys(_m)
}

// QueryRedeemCodes queries the "redeem_codes" edge of the User entity.
func (_m *User) QueryRedeemCodes() *RedeemCodeQuery {
	return NewUserClient(_m.config).QueryRedeemCodes(_m)
}

// QuerySubscriptions queries the "subscriptions" edge of the User entity.
func (_m *User) QuerySubscriptions() *UserSubscriptionQuery {
	return NewUserClient(_m.config).QuerySubscriptions(_m)
}

// QueryAssignedSubscriptions queries the "assigned_subscriptions" edge of the User entity.
func (_m *User) QueryAssignedSubscriptions() *UserSubscriptionQuery {
	return NewUserClient(_m.config).QueryAssignedSubscriptions(_m)
}

// QueryAnnouncementReads queries the "announcement_reads" edge of the User entity.
func (_m *User) QueryAnnouncementReads() *AnnouncementReadQuery {
	return NewUserClient(_m.config).QueryAnnouncementReads(_m)
}

// QueryAllowedGroups queries the "allowed_groups" edge of the User entity.
func (_m *User) QueryAllowedGroups() *GroupQuery {
	return NewUserClient(_m.config).QueryAllowedGroups(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the User entity.
func (_m *User) QueryUsageLogs() *UsageLogQuery {
	return NewUserClient(_m.config).QueryUsageLogs(_m)
}

// QueryAttributeValues queries the "attribute_values" edge of the User entity.
func (_m *User) QueryAttributeValues() *UserAttributeValueQuery {
	return NewUserClient(_m.config).QueryAttributeValues(_m)
}

// QueryPromoCodeUsages queries the "promo_code_usages" edge of the User entity.
func (_m *User) QueryPromoCodeUsages() *PromoCodeUsageQuery {
	return NewUserClient(_m.config).QueryPromoCodeUsages(_m)
}

// QueryUserAllowedGroups queries the "user_allowed_groups" edge of the User entity.
func (_m *User) QueryUserAllowedGroups() *UserAllowedGroupQuery {
	return NewUserClient(_m.config).QueryUserAllowedGroups(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(_m.PasswordHash)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("concurrency=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrency))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("admin_free_billing=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdminFreeBilling))
	builder.WriteString(", ")
	builder.WriteString("request_details_review=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestDetailsReview))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("usage_model_display_mode=")
	builder.WriteString(_m.UsageModelDisplayMode)
	builder.WriteString(", ")
	builder.WriteString("global_realtime_countdown_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.GlobalRealtimeCountdownEnabled))
	builder.WriteString(", ")
	builder.WriteString("account_realtime_countdown_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountRealtimeCountdownEnabled))
	builder.WriteString(", ")
	builder.WriteString("visual_preset_preference=")
	builder.WriteString(_m.VisualPresetPreference)
	builder.WriteString(", ")
	builder.WriteString("account_visual_preset_override=")
	builder.WriteString(_m.AccountVisualPresetOverride)
	builder.WriteString(", ")
	builder.WriteString("account_today_stats_windows=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountTodayStatsWindows))
	builder.WriteString(", ")
	builder.WriteString("account_today_stats_cycle_mode=")
	builder.WriteString(_m.AccountTodayStatsCycleMode)
	builder.WriteString(", ")
	builder.WriteString("account_group_display_mode=")
	builder.WriteString(_m.AccountGroupDisplayMode)
	builder.WriteString(", ")
	builder.WriteString("account_status_display_mode=")
	builder.WriteString(_m.AccountStatusDisplayMode)
	builder.WriteString(", ")
	builder.WriteString("usage_context_badge_display_mode=")
	builder.WriteString(_m.UsageContextBadgeDisplayMode)
	builder.WriteString(", ")
	builder.WriteString("api_key_model_binding_mode=")
	builder.WriteString(_m.APIKeyModelBindingMode)
	builder.WriteString(", ")
	builder.WriteString("external_model_catalog_view_mode=")
	builder.WriteString(_m.ExternalModelCatalogViewMode)
	builder.WriteString(", ")
	builder.WriteString("api_key_access_time_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyAccessTimePolicy))
	builder.WriteString(", ")
	if v := _m.TotpSecretEncrypted; v != nil {
		builder.WriteString("totp_secret_encrypted=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("totp_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotpEnabled))
	builder.WriteString(", ")
	if v := _m.TotpEnabledAt; v != nil {
		builder.WriteString("totp_enabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
