// Code generated by ent, DO NOT EDIT.

package apikeygroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldGroupID, v))
}

// Quota applies equality check predicate on the "quota" field. It's identical to QuotaEQ.
func Quota(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldQuota, v))
}

// QuotaUsed applies equality check predicate on the "quota_used" field. It's identical to QuotaUsedEQ.
func QuotaUsed(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldQuotaUsed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// QuotaEQ applies the EQ predicate on the "quota" field.
func QuotaEQ(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldQuota, v))
}

// QuotaNEQ applies the NEQ predicate on the "quota" field.
func QuotaNEQ(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNEQ(FieldQuota, v))
}

// QuotaIn applies the In predicate on the "quota" field.
func QuotaIn(vs ...float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIn(FieldQuota, vs...))
}

// QuotaNotIn applies the NotIn predicate on the "quota" field.
func QuotaNotIn(vs ...float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotIn(FieldQuota, vs...))
}

// QuotaGT applies the GT predicate on the "quota" field.
func QuotaGT(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGT(FieldQuota, v))
}

// QuotaGTE applies the GTE predicate on the "quota" field.
func QuotaGTE(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGTE(FieldQuota, v))
}

// QuotaLT applies the LT predicate on the "quota" field.
func QuotaLT(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLT(FieldQuota, v))
}

// QuotaLTE applies the LTE predicate on the "quota" field.
func QuotaLTE(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLTE(FieldQuota, v))
}

// QuotaUsedEQ applies the EQ predicate on the "quota_used" field.
func QuotaUsedEQ(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldQuotaUsed, v))
}

// QuotaUsedNEQ applies the NEQ predicate on the "quota_used" field.
func QuotaUsedNEQ(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNEQ(FieldQuotaUsed, v))
}

// QuotaUsedIn applies the In predicate on the "quota_used" field.
func QuotaUsedIn(vs ...float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIn(FieldQuotaUsed, vs...))
}

// QuotaUsedNotIn applies the NotIn predicate on the "quota_used" field.
func QuotaUsedNotIn(vs ...float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotIn(FieldQuotaUsed, vs...))
}

// QuotaUsedGT applies the GT predicate on the "quota_used" field.
func QuotaUsedGT(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGT(FieldQuotaUsed, v))
}

// QuotaUsedGTE applies the GTE predicate on the "quota_used" field.
func QuotaUsedGTE(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGTE(FieldQuotaUsed, v))
}

// QuotaUsedLT applies the LT predicate on the "quota_used" field.
func QuotaUsedLT(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLT(FieldQuotaUsed, v))
}

// QuotaUsedLTE applies the LTE predicate on the "quota_used" field.
func QuotaUsedLTE(v float64) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLTE(FieldQuotaUsed, v))
}

// QuotaUsedByCurrencyIsNil applies the IsNil predicate on the "quota_used_by_currency" field.
func QuotaUsedByCurrencyIsNil() predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIsNull(FieldQuotaUsedByCurrency))
}

// QuotaUsedByCurrencyNotNil applies the NotNil predicate on the "quota_used_by_currency" field.
func QuotaUsedByCurrencyNotNil() predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotNull(FieldQuotaUsedByCurrency))
}

// ModelPatternsIsNil applies the IsNil predicate on the "model_patterns" field.
func ModelPatternsIsNil() predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIsNull(FieldModelPatterns))
}

// ModelPatternsNotNil applies the NotNil predicate on the "model_patterns" field.
func ModelPatternsNotNil() predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotNull(FieldModelPatterns))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyGroup {
	return predicate.APIKeyGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, APIKeyColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.APIKeyGroup {
	return predicate.APIKeyGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, GroupColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyGroup) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyGroup) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyGroup) predicate.APIKeyGroup {
	return predicate.APIKeyGroup(sql.NotPredicates(p))
}
