// Code generated by ent, DO NOT EDIT.

package passkeyuserhandle

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldUserID, v))
}

// UserHandle applies equality check predicate on the "user_handle" field. It's identical to UserHandleEQ.
func UserHandle(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldUserHandle, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNotIn(FieldUserID, vs...))
}

// UserHandleEQ applies the EQ predicate on the "user_handle" field.
func UserHandleEQ(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldEQ(FieldUserHandle, v))
}

// UserHandleNEQ applies the NEQ predicate on the "user_handle" field.
func UserHandleNEQ(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNEQ(FieldUserHandle, v))
}

// UserHandleIn applies the In predicate on the "user_handle" field.
func UserHandleIn(vs ...[]byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldIn(FieldUserHandle, vs...))
}

// UserHandleNotIn applies the NotIn predicate on the "user_handle" field.
func UserHandleNotIn(vs ...[]byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldNotIn(FieldUserHandle, vs...))
}

// UserHandleGT applies the GT predicate on the "user_handle" field.
func UserHandleGT(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGT(FieldUserHandle, v))
}

// UserHandleGTE applies the GTE predicate on the "user_handle" field.
func UserHandleGTE(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldGTE(FieldUserHandle, v))
}

// UserHandleLT applies the LT predicate on the "user_handle" field.
func UserHandleLT(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLT(FieldUserHandle, v))
}

// UserHandleLTE applies the LTE predicate on the "user_handle" field.
func UserHandleLTE(v []byte) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.FieldLTE(FieldUserHandle, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PasskeyUserHandle) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PasskeyUserHandle) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PasskeyUserHandle) predicate.PasskeyUserHandle {
	return predicate.PasskeyUserHandle(sql.NotPredicates(p))
}
